### ISSUE TITLE
get_unit_spike_times enhancement request

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#1000]
## Feature Request
For long datasets it would be very helpful to be able to select an observation interval to slice the spike times so that only the times in a specified interval were returned. 

If that's possible, it would also be helpful to be able to specify a list of unit_id so that a single call could return a list of units with spike times in the given interval. 

e.g.

unit_spike_times = nwbf.units.get_unit_spike_times((1,4,5,23), [start_time, end_time])

where unit spikes times would be a list, with one element per unit, and each element would be a list of spike times. Alternatively, unit_spike_times could be a pandas table.

This would also be useful for the nwb-datajoint interface, as it would make it easier to load all of the desired data from a schema query with a single function call. 

### Problem/Use Case
In our datasets we have > 2000 units, each recorded for >= 24 hours. The result is O(10^6) spikes for some units, so loading the entire set of times for many units will be problematic. As these sorts of datasets become more common, this issue will be something that more and more people face.

**Comment by bendichter** [comment]
This seems pretty straightforward to implement

**Comment by lfrank** [comment]
Happy to hear that it would be straightforward. Is it something you'd feel comfortable doing or more of an Andrew / Oliver level change?

**Comment by bendichter** [comment]
I can do it

**Comment by bendichter** [comment]
I think the syntax change should be to add an argument `in_interval` to `nwbf.units.get_unit_spike_times` that can be:
* `None` (default): return all times 
* `(Float, Float)`: return times only in this interval (start and stop in seconds)

we could also add an option:

* `[(Float, Float), (Float, Float), ... ]` return times in any of these intervals. This could be useful for things like trials, though it's really just a convenience function since this can easily be accomplished by calling with the previous form in a loop.

**Comment by bendichter** [comment]
OK, #1001 should do it. One consideration is the boundary case of when a spike time exactly equals either the lower or upper bound. I include the spikes in this case but it would be straightforward to exclude for the lower bound, the upper bound, or both.
