### ISSUE TITLE
TypeError: missing argument 'source'

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#101]
error on initializing an NWBFile object:

```
TypeError: missing argument 'source'
```

checking the NWBFile docstring, I see that source is a required argument...

```
Init signature: NWBFile(*args, **kwargs)
Docstring:      A representation of an NWB file.
Init docstring:
__init__(source, file_name, session_description, identifier, session_start_time, file_create_date=None, experimenter=None, experiment_description=None, session_id=None, institution=None, lab=None, raw_timeseries=None, stimulus=None, stimulus_template=None, epochs=None, modules=None, ec_electrodes=None, ic_electrodes=None, imaging_planes=None, optogenetic_sites=None, devices=None)

Args:
    source (str): the source of the data
    file_name (str): path to NWB file
    session_description (str): a description of the session where this data was generated
    identifier (str): a unique text identifier for the file
    session_start_time (datetime or str): the start time of the recording session
    file_create_date (list or datetime or str): the time the file was created and subsequenct modifications made
    experimenter (str): name of person who performed experiment
    experiment_description (str): general description of the experiment
    session_id (str): lab-specific ID for the session
    institution (str): institution(s) where experiment is performed
    lab (str): lab where experiment was performed
    raw_timeseries (list or tuple): Raw TimeSeries objects belonging to this NWBFile
    stimulus (list or tuple): Stimulus TimeSeries objects belonging to this NWBFile
    stimulus_template (list or tuple): Stimulus template TimeSeries objects belonging to this NWBFile
    epochs (list or tuple): Epoch objects belonging to this NWBFile
    modules (list or tuple): ProcessingModule objects belonging to this NWBFile
    ec_electrodes (list or tuple): ElectrodeGroups that belong to this NWBFile
    ic_electrodes (list or tuple): IntracellularElectrodes that belong to this NWBFile
    imaging_planes (list or tuple): ImagingPlanes that belong to this NWBFile
    optogenetic_sites (list or tuple): OptogeneticStimulusSites that belong to this NWBFile
    devices (list or tuple): Device objects belonging to this NWBFile
```

however, I don't see "source" in the nwb-schema documentation:
http://nwb-schema.readthedocs.io/en/latest/format.html#main-data-file

what is this argument and why is it required?

**Comment by oruebel** [comment]
```source``` is inherited from ```NWBContainer``` and is defined as a string describing the source of the data in the container.  

One main change to the format as a result of the last hackathon at Janelia  was that "Interface" was renamed to "NWBContainer" and "NWBContainer" was moved up the inheritance hierarchy to be a basic common type. This change was made 1) to avoid confusion as the term Interface was perceived as having multiple different interpretations, 2) to enable analysis containers to inherit from TimeSeries directly (this was not possible because all analyses were required to be an Interface and hence could not be a TimeSeries as well), 3) to create a common base container were concepts, such as, provenance etc. could be added to in the future, and 4) I believe there were some more reasons as well that I would need to look up.  As a result of this change, "source" and "help" have become required on a number of types that were previously missing those fields.

**Comment by neuromusic** [comment]
I see.

Is there a reason that the documentation isn't getting updated along with the changes to the schema and pynwb?

**Comment by oruebel** [comment]
I updated the docs on an nwb-schema branch but it has not been rolled out yet. Generating the format docs from the schema requires running the generateFormatDocs.py script first to general the sources for the Sphinx docs. Currently ReadTheDocs only takes care of the build of the docs but not the generation of the source files for the docs. I need to check whether we can just call the generateFormatDocs as part of the conf.py of the Sphinx docs without breaking ReadTheDocs. I'll create a seperate issue for this next.

**Comment by oruebel** [comment]
Here the ticket I generate for this: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/55

**Comment by oruebel** [comment]
Here the new ticket for the proposal to make source optional on NWBContainer: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/56
