### ISSUE TITLE
rename `NWBFile` -> `NWBSession`

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#106]
the object which abstracts the NWB data model from the backend implementation should be agnostic to the backend

NWBFile presumes that the session is a single file... it should be renamed to something more abstract, like "NWBSession"

**Comment by oruebel** [comment]
The class NWBFile represents the type NWBFile defined in the spec. The concept of an NWBSession I think would probably exists alongside or live above NWBFile rather than replacing it. I think this is an item we should probably revisit once we get into actually implementing non-file backends for NWB.

**Comment by neuromusic** [comment]
well @nicain is already getting into implementing non-file backends so the time is now :)
