### ISSUE TITLE
conversion_factor per channel

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1064]
## Feature Request
We are running into a suboptimal situation storing neuropixel data from a SpikeGLX acquisition system. The system stores a conversion factor *per channel*. We can get this data into NWB by just multiplying the conversion factors across the channels and storing floats in Volts, but then we are dramatically increasing the file size. Neuropixel data is very big, so this is really not an ideal solution. Would there be any convenient way to represent conversion_factor in a per-channel way?

cc @luiztauffer

**Comment by ajtritt** [comment]
@bendichter what are they currently stored as?

**Comment by bendichter** [comment]
@ajtritt it is currently stored as a float that is used for all of the channels

**Comment by oruebel** [comment]
@bendichter I assume the data itself is then stored as ints (rather than floats)? 

Could you clarify the reason for the per-channel conversion factor? Is the variability between channels so large that they have to be scaled independently, or could the factors be harmonized?

I think to properly represent conversion_factor on a per-channel basis would require an update to the schema to allow conversion to be an array. 

On a separate note, it would be useful to have a feature in the API to allow the user to get data with the conversion factor(s) already applied, but that's a discussion for another issue.

**Comment by bendichter** [comment]
@oruebel

I don't know why they store the conversion factors this way. It's uncommon, but it may be due to very different ranges. I suppose it may be possible to re-digitize the values on a uniform scale.

**Comment by rly** [comment]
> @bendichter I assume the data itself is then stored as ints (rather than floats)?

If a conversion factor is used, then the data is usually stored as ints. 

> Could you clarify the reason for the per-channel conversion factor? Is the variability between channels so large that they have to be scaled independently, or could the factors be harmonized?

The variability between channels can be quite large depending on which amplifiers are used for each electrode and where the electrodes are. Some acquisition systems allow for per-channel conversion factors or gains. I've used this before on one of the newer systems in my grad school lab.

> I think to properly represent conversion_factor on a per-channel basis would require an update to the schema to allow conversion to be an array.

That is what I'm thinking too.

```yaml
  datasets:
  - name: data
    [...]
    attributes:
    - name: conversion
      dtype: float32
      default_value: 1.0
      dims:
        - num_channels
      shape:
        - null
```

> On a separate note, it would be useful to have a feature in the API to allow the user to get data with the conversion factor(s) already applied, but that's a discussion for another issue.

Totally agree.

**Comment by bendichter** [comment]
So would this be overloading the current conversion attribute? Will that break backwards compatibility?

**Comment by oruebel** [comment]
> So would this be overloading the current conversion attribute? Will that break backwards compatibility?

We definitely don't want to break backward compatibility for this (in particular since this is on the base TimeSeries type). The idea  I think would be to either allow a single float (as is right now) that would apply to all channels, or an array that would then be on a per-channel basis.

**Comment by rly** [comment]
@oruebel , @ajtritt , and I were debating this today. Here is our tentative idea: Add a dataset called `conversion_factor` on `ElectricalSeries` with an attribute called `axis` fixed to 1 (to correspond to the second dimension of `data`). To get the actual data in Volts, you have to multiply your `data` dataset by both the global `conversion` attribute on `data` and the dataset `conversion_factor` which would have per-channel gains or whatever else is required for per-channel conversion. How does this sound?

**Comment by bendichter** [comment]
The axis attribute sounds like a good idea. I think it's a bit silly to multiply twice, but if it is important for backwards compatibility then it's a workable solution. I'd rather name the dataset something like `channel_conversion` to make it more clear how they are different.

**Comment by oruebel** [comment]
>  I'd rather name the dataset something like `channel_conversion`

That sounds like a reasonable name.

>  I think it's a bit silly to multiply twice,

I agree, but creating a special case where folks would need to ignore the conversion factor from TimeSeries if ``channel_conversion`` is present gets unfortunately even messier. In most cases, I don't think it will make a difference, because if you have ``channel_conversion`` than the scalar conversion factor will in most cases be set to ``1`` anyways. 

Part of the issues is that changing the conversion factor on the base TimeSeries gets tricky not just for backward compatibility but in part because implementing multi-dimensional conversion factors is non-trivial in a general and reusable way. The special case of ElectricalSeries, however is much simpler.

**Comment by bendichter** [comment]
Yeah that all makes sense. I think this solution is reasonable and will solve the current problem.
