### ISSUE TITLE
saving with "to_X()" methods on NWBFile

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#117]
idea for discussion:

I really like the way that pandas handles saving & converting data to various formats. Basically, any target format, whether that's saving to disk or converting to another python data format, uses the same syntax: methods on the object of the format "to_X" where X is the target format.

```
nwb_file.to_hdf('my_data.nwb')
```

this simplifies file saving for the user... they don't need to understand anything about `form` at all. further, they can readily discover supported target formats with simple tab completion.

obviously, behind the scenes this would be a simple wrapper for form's HDF5IO

similarly, one could imagine e.g. converting to an xarray with syntax like

```
xr_dataset = nwb_file.to_xarray()
```

**Comment by oruebel** [comment]
I like the idea, but I would probably make it part of a separate I/O package in PyNWB rather than adding I/O-specific functions directly to NWBFile, but that's just implementation details.

**Comment by neuromusic** [comment]
To clarify, the proposal here is quite specifically to add these as method calls directly on the NWBFile instance.

**Comment by ajtritt** [comment]
Adding these method calls would require the NWBFile class to have a dependency on a backend implementation and the object-relational mapping layer. I'd prefer to keep these classes agnostic to these parts of form.

I added another scenario to the Gist demonstrating different I/O scenarios. This demonstrates what @oruebel suggested.
https://gist.github.com/ajtritt/11f2bda4846a96eb67cd9e9a7e1b2bdc#file-io_scenarios-py-L76

Users could still discover by tab-completion, but it would have to be on package. Would that be okay?

**Comment by neuromusic** [comment]
>  I'd prefer to keep these classes agnostic to these parts of form.

Um... why?
 
1. pynwb already has a dependency on form
1. form has a handful of backends that it explicitly supports

I don't see any technical problem with adding backend-aware methods on the class, whereas the usability benefits of saving from a method directly on the data object are substantial.

**Comment by ajtritt** [comment]
Um, because, apart from some basic utilities in form, NWBFile and other Container classes actually have almost no dependency on form. These are the classes that users interface with

**Comment by ajtritt** [comment]
Um, because, apart from some utilities supplied by form, NWBFile and other Container classes (classes in the ecephys, icephys, ophys, ogen, image, behavior, and misc submodules)  actually have no dependency on the major components that make up form i.e. backend and object-relational mapping. These are the classes that users interface with. Keeping them separate from the intricacies of FORM ensure a stable interface to NWB for users. 

> 1. pynwb already has a dependency on form

It's not that simple. pynwb's dependencies lie on the top of the package (in __init__), through the use of the ORM data structures, and in pynwb.io, where custom mappers are defined. The rest of the pynwb package is separated from form.

> 2. form has a handful of backends that it explicitly supports

Actually, right now it only supports one backend. But, assuming it did have more than one, which it is designed to supprt, can you clarify why this has anything to do with what you've suggested? If anything, this is an argument against your proposed feature. For every backend, we have to edit NWBFile to add some new `to_<backend>` method to it. It makes the code much less modular, and creates more dependencies.

> I don't see any technical problem with adding backend-aware methods on the class, whereas the usability benefits of saving from a method directly on the data object are substantial.

I'm sure you don't see any technical problem with this, since you haven't actually contributed to this code base nor understand how it actually works. Until you actually understand what's going on, we'd prefer that you don't make requests to major infrastructural overhauls.

**Comment by nicain** [comment]
Sorry all, I am behind on this one.

I am having trouble finding the implementation of pynwb.to_hdf5 referenced in https://gist.github.com/ajtritt/11f2bda4846a96eb67cd9e9a7e1b2bdc#file-io_scenarios-py-L84.  Is this in dev, or some other branch i can take a look at?

**Comment by ajtritt** [comment]
@nicain The code for those examples exists on enh/explicit_io, which isn't fully tested. I haven't added pynwb.to_hdf5 yet--I just added it to that script as a proposal for you guys to see.

**Comment by nicain** [comment]
@ajtritt Got it, thanks!  My two cents is that this method deserves a different name.  By looking at your gist and guessing at what it does, it might be better to call it something like: 

```Python
get_hdfio_serializer(nwbfile, foo_ext_path)
```

This might seem like a trivial thing (please don't take this wrong, only trying to be productive, not sniping!), but methods should be named according to what they do.  Also, this frees up the to_hdf5 method for an extremely lightweight implementation that could provide the UX that I think @neuromusic could get behind:

```Python
def to_hdf5(self, nwbfile, foo_ext_path):
    io = pynwb.get_hdfio_serializer(nwbfile, foo_ext_path)
    io.write(nwbfile)
    io.close()
```

This type of minimal extension to the class is easy enough to maintain, and in my opinion would provide a UX that is worth its maintenance costs.

As a side note, in either case, I would name this to_hdf instead (in analogy to pandas), so that it is easy to remember.

**Comment by neuromusic** [comment]
like I said, I don't see any technical problem with adding backend-aware methods on the class

**Comment by neuromusic** [comment]
> assuming it did have more than one, which it is designed to supprt, can you clarify why this has anything to do with what you've suggested?

yes, I can. 

there are two ways this can be implemented.

The first is for the pynwb community to make a decision about what backends are of sufficient popularity to merit file saving using to_X() methods. In this case, each can be implemented on its own, with it's own documentation.

However, if there are more than a handful of backends and we want to support ALL of them, this may become burdensome to maintain. My comment was in anticipation of this response.

The other way, which I have implemented in #121 is for the NWBFile class to automatically discover the FORMIO backends that it has access to and dynamically create "methods" (not really methods, though) on init. This has the benefit of being comprehensive, but has the risk of being sensitive to the module structure of `form.backends` and the arguments that each of the FORMIO classes requires. It also makes documentation a bit trickier.

**Comment by ajtritt** [comment]
@nicain Thanks for the suggestion. Are you suggesting replacing `NWBHDF5IO` with `get_hdfio_serializer` ?

**Comment by ajtritt** [comment]
@neuromusic Can you explain what the value add is here? From my perspective, #121 creates a significant dependency for pynwb on the form.backends subpackage. In addition, because it is dynamically adding methods to NWBFile it is setting NWBFile up to be unstable, which our design is intended to prevent. Finally, it implicitly adds methods to NWBFile... the rule is... the subpackage name becomes the suffix of a method for using a writer class that was defined in said subpackage... this doesn't seem consistent with the explicit-is-better-than-implicit philosophy we want to adhere to. The rule sets us up for future collsions... What happens in the case when add the subpackage `form.backends.reldb` that has the two classes `PostgresIO` and `MySQLIO`? 

All of these bad design decisions so the users can type `nwbfile.to_hdf5(...)` instead of `pynwb.to_hdf5(nwbfile)`... Seems like a lot of technical debt to take on for a rather inconsequential feature.

**Comment by neuromusic** [comment]
>Can you explain what the value add is here? 

It is a common, intuitive syntax for saving files and converting data structures that pynwb users will likely be familiar with.

There are over 65,000 hits for files on github that have "df.to_csv" in them: https://github.com/search?q=%22df.to_csv%22&type=Code&utf8=%E2%9C%93 & other packages that use the syntax

**pandas**
- `to_csv`,`to_excel`,`to_json`,`to_xarray` etc 
- https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

**xarray**
- `to_netcdf`, `to_dataframe`, `to_dict` etc
- http://xarray.pydata.org/en/stable/api.html#dataarray-methods

**MNE** 
- `to_data_frame` 
- http://martinos.org/mne/stable/generated/mne.Epochs.html#mne.Epochs.to_data_frame

**PySpark**
- `toPandas` (yes, I know this specific implementation breaks the "standard")
- http://spark.apache.org/docs/2.1.0/api/python/pyspark.sql.html#pyspark.sql.DataFrame.toPandas

**dask**
- `to_hdf`, `to_bag`, `to_csv`
- http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.to_hdf

I fully acknowledge that there are tradeoffs in the implementation & for all the reasons you highlight, I think that being explicit with which FORM backends will be supported through this syntax is probably the best approach.

As our first candidate, I propose a single `to_hdf` method on NWBFile as a wrapper for the HDF5IO backend & that we consider other methods that fit this syntax as the needs arise.

**Comment by oruebel** [comment]
As far as I can tell, the main point of discussion is whether the to_*** functions should live on NWBFile or not. I understand why the to_*** syntax helps makes things feel familiar and it sounds like there is agreement that we want to have those functions. However, I'm not quite sure why those functions would need to live on NWBFile compared to a dedicated io package. Numpy, e.g., also does not have those functions live on the actual array but users call numpy.save, numpy.from_file, etc. The pynwb.to_hdf seems to be essentially that approach, and I think it works well. Ultimately, I don't think it makes a huge difference from a user perspective whether to call NWBFile.to_hdf or pynwb.to_hdf. However, from a software design perspective the latter seems much cleaner and easier to maintain.

**Comment by neuromusic** [comment]
>Numpy, e.g., also does not have those functions live on the actual array but users call numpy.save, numpy.from_file, etc. 

**numpy**
- `tolist`,`tostring`,`tobytes`,`tofile`
- https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

**Comment by oruebel** [comment]
The ```tolist``` etc. functions are for in-memory conversion not for I/O. I believe for all non-numpy-specific I/O, e.g., for read/write of csv, flat binary etc. the functions live only on numpy and not the array.

**Comment by ajtritt** [comment]
Is this convenient feature worth putting the code in a state that sacrifices flexibility and maintainability? Is the alternative (leaving these as functions on the package) so confusing to users that we should create a rats nest of dynamically created instance methods and implicit naming conventions?

**Comment by neuromusic** [comment]
@oruebel see "tofile" as I listed above
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tofile.html#numpy.ndarray.tofile

**Comment by ajtritt** [comment]
@nicain I just realized I made a copy-paste mistake in the Gist. The module function `to_hdf5` should not return an object that users have to make subsequent calls with. I changed it to reflect what I meant.

https://gist.github.com/ajtritt/11f2bda4846a96eb67cd9e9a7e1b2bdc#file-io_scenarios-py-L84

**Comment by ajtritt** [comment]
I made another revision to simplify the  calls to NWBHDF5IO. The following lines should demonstrate the `pynwb.to_hdf5` function...

https://gist.github.com/ajtritt/11f2bda4846a96eb67cd9e9a7e1b2bdc#file-io_scenarios-py-L53
https://gist.github.com/ajtritt/11f2bda4846a96eb67cd9e9a7e1b2bdc#file-io_scenarios-py-L69

**Comment by neuromusic** [comment]
fantastic. this/these will be even easier/cleaner to wrap with NWBFile method(s) than my PR.

**Comment by ajtritt** [comment]
Does this make an append method easier, too?

**Comment by nicain** [comment]
This looks awesome to me!

**Comment by neuromusic** [comment]
@ajtritt an append method?

**Comment by ajtritt** [comment]
Yes, append, meaning writing additional data to an existing file. I have had requests for the ability to write analysis results back the file from which the input data came. How does `NWBFile.to_hdf5` instance method do this? Also, with read/write as methods on NWBFile, how would you handle reading? Create a `NWBFile.from_hdf5` class method?

**Comment by neuromusic** [comment]
> How does NWBFile.to_hdf5 instance method do this?

You don't have an example of appending with the `pynwb.to_hdf` function... So I assume that appending would need to happen using the HDF5IO class, as in your example.

> Also, with read/write as methods on NWBFile, how would you handle reading? Create a NWBFile.from_hdf5 class method?

I'm not proposing a read method on NWBFile. Exposing this as a class method would be confusing for most users, I think. One would read with `pynwb.NWBHDF5IO` then `io.read()` as in your example (or by combining these into `nwbfile = pynwb.read_hdf('experiment.nwb')` to be more consistent with other packages).
