### ISSUE TITLE
'form' is pretty ambiguous when it comes to python packaging

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#118]
there are lots of existing python packages that call themselves "form" such that a pynwb user may experience some weird consequences if one of these packages is installed on their python path

we should consider renaming form to something more unique

**Comment by jcfr** [comment]
Agreed.

@oruebel @mgrauer @nicain  

* What do you think ? What is the relationship of the `form` module with [nwb-schema](https://github.com/NeurodataWithoutBorders/nwb-schema) ? 

* Should we relocate `src/form` to `src/pynwb/format` ? Or move the code to its own repo  ?

Cc: @dorukozturk

**Comment by mgrauer** [comment]
I agree that this collision is best avoided.

I had had some previous confusion as to the name, if I remember the conversation correctly, I was told that the 'orm' in 'form' stood for "object relational mapper" but that it isn't actually an object relational mapper, such as in the common usage like sqlalchemy. If this is true, avoiding this kind of confusion also suggests a renaming.

/cc @kotfic @ajtritt

**Comment by ajtritt** [comment]
I always considered it an ORM, because it maps data stored in HDF5 to a data model defined using base classes from FORM. But if it's confusing, we should just ditch that concept.

I have no feelings on what it gets named. I doubt it has any utility outside of PyNWB, so it might just make the most sense to move it to a subpackage of PyNWB that's hidden from the public.

**Comment by oruebel** [comment]
I like the separation of the two packages, if only because it makes the separation of front-end data classes and underlying infrastructure explicit. Which helps also in communicating the process. 

With regard to names. I'd suggest we start a google doc to collect suggestions and then we can pick a new name. I'll send out a doc later and add it to the agenda for our next telecon.

**Comment by oruebel** [comment]
Form will be moved into pynwb as pynwb/form as indicated in #156.

**Comment by oruebel** [comment]
Pull request #167 resolves this issue.
