### ISSUE TITLE
backwards compatibility issues in ipfx

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1186]
When trying to update ipfx from pynwb==1.0.1 to pynwb==1.2.1, I run into this error:

```python
TypeError: VoltageClampStimulusSeries.__init__: unrecognized argument: 'unit'
```

The `unit` arg was removed because it is fixed in the schema. Could we put it back and include a warning that it will not be used?

**Comment by rly** [comment]
In PyNWB 1.1.0, we changed the function signature of `PatchClampSeries` subtypes to remove the `unit` argument, which became hardcoded to `'amperes'` or `'volts'` according to the updated schema. In retrospect, this was a serious mistake as it breaks backward compatibility with code that instantiates one of these objects _using positional arguments_.

I see two approaches moving forward here:
1) Add the `unit` argument back as a required positional argument to `PatchClampSeries` subtypes in the same place as it was in PyNWB 1.0 (between required args `data` and `electrode`). This retains backward compatibility with PyNWB 1.0 but breaks compatibility with PyNWB 1.1 for any calling code that uses positional arguments. 
2) Add the `unit` argument back as an optional positional argument to `PatchClampSeries` subtypes at the end of the argument list. This breaks backward compatibility with PyNWB 1.0 but retains compatibility with PyNWB 1.1 for any calling code that uses positional arguments.

Regardless of which approach, if the supplied `unit` argument is not the hard-coded `unit` value in the schema, then ignore it and raise a warning that the `unit` argument will be ignored.

The compatibility issue only affects code that calls `__init__` on these types with positional arguments. I am inclined to do #1 and treat the removal of the `unit` argument in PyNWB 1.1 as a bug. 

Ultimately, I think we should discourage and eventually disallow positional arguments from being passed to constructors, so that we are free to change the required-ness and order of constructor arguments in PyNWB as the schema is updated. (I will expand upon this idea in a separate issue, later.)

**Comment by bendichter** [comment]
I'm strongly in favor of 2. Getting people to change from a positional to kwarg will not be hard. Forcing them to include incorrect information will be confusing for everyone and will break compatibility for the current version

**Comment by rly** [comment]
> Forcing them to include incorrect information will be confusing for everyone and will break compatibility for the current version

To be clear, they would not be including incorrect information. Just extraneous information. e.g., `unit='volts'` would have to be passed in every time. But point taken. I now think 2 is better.
