### ISSUE TITLE
add FAQ to docs

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#119]
for this major release, it might be worth assembling an FAQ for anticipated questions & as a way to walk people through the major changes in the architecture of this release.

things like...

- What are the major updates in this new API? (separation of API, specification, & backend storage)
- Does the new API offer support? (yes)
- Have there been any changes to the schema? (yes: ElectrodeGroup, Tables, etc.)
- Can the new API read old NWB files? (there is limited support for allen institute files)
- What if I have data that doesn't fit the schema? (build an extension)

**Comment by oruebel** [comment]
Having an FAQ sounds like a good idea. Just a few thoughts, we probably want to have the high-level summary of the items you mentioned live on the nwb.org website and point to the docs for details. For the "what has changed" question, the following should hopefully be a good start: http://nwb.org/2017/09/06/what-is-new-in-nwbn-v2-0/ . 

For details on what has changed in the format and specification language, we should refer folks to the release notes:

* http://schema-language.readthedocs.io/en/latest/specification_language_release_notes.html these are the release notes for the specification language
* http://nwb-schema.readthedocs.io/en/latest/format.html#a-may-2017 these are the format/schema release notes. 

I've tried to keep notes in the release notes of at least all the major changes as they were implemented,  however, they still need a bit of clean-up and updated. Specifically, I need to update the description for electrode group and epoch since those are going to undergo some more changes. A number of other changes that are currently not yet in the ReadTheDocs version (e.g. update of the version number, description of NWBContainer vs. Interface etc.) are already on a pull request that I need to merge in.

**Comment by mgrauer** [comment]
These questions were asked on the NWB Slack channel, so they have a count of at least 1.

1) What is the difference between pynwb, nwb-schema and api-python? I intend to write a GUI to convert the experiments carried out at our group to NWB format. Do I need all of them? 
2) How do I install pynwb? I can't find installation instructions in the repo. I have already installed api-python - will they conflict?
3) Are both python 2.7 and python 3.5 supported?
4) How significant do you envision the changes to interface to be between now and full release of 2.0? Does it make sense to start using NWB now, or is it more sensible to wait?

**Comment by neuromusic** [comment]
to prevent confusion for our users, I just added "DEPRECATED" to the descriptions for the following repositories:

- api-python
- api-matlab
- specification
- visualization

We should probably update their READMEs to point to the corresponding 2.0 repos.

**Comment by oruebel** [comment]
The FAQ page is available at https://neurodatawithoutborders.github.io/faq and there is also a getting started page here https://neurodatawithoutborders.github.io/gettingstarted . These pages are part of the https://github.com/NeurodataWithoutBorders/neurodatawithoutborders.github.io repo
