### ISSUE TITLE
Backwards compatibility issue: accessing roi_response_data in latest version

### ISSUE THREAD

**Issue by chriski777** [NeurodataWithoutBorders/pynwb#1283]
Hello, after updating to the latest version of `pynwb`, we started running into an issue with accessing `roi_response_data`.

The following code block worked with v1.3.3:
```
with NWBHDF5IO(fpath, 'r') as fio:
    nwbfile = fio.read()
    ...
    F = np.array(nwbfile.processing['ophys']['Fluorescence']['roi_response_series'].data)
```

With the new release (v1.4.0), we get the following error:
```
KeyError: "'roi_response_series' not found in Fluorescence 'Fluorescence'."
```

**Comment by rly** [comment]
@chriski777 thanks for the bug report. What is the name of the `RoiResponseSeries` object in the `Flourescence` object?

And what does `print(nwbfile.processing['ophys']['Fluorescence'])` print?

**Comment by rly** [comment]
These lines:
https://github.com/MouseLand/suite2p/blob/58c9036ee2d97fe80d5a822b4685a6d7e11ec428/suite2p/io/nwb.py#L253-L261

create an `RoiResponseSeries` object that is named one of {'Fluorescence', 'Neuropil', 'Deconvolved'} and adds that object to a `Fluorescence` container with the same name.

To access the `RoiResponseSeries` object with name 'x' from a `Fluorescence` variable called 'fl', use the syntax `fl['x']`. I will create a PR in suite2p to fix it.

The previous code worked but should not have worked -- this was a bug. If a `MultiContainerInterface` such as `Fluorescence` or `LFP` contained a single Container, then you could use `multi_container_interface['any string']` to get that Container, even if the key did not match the name of the Container. Now an error is returned. (If the `MultiContainerInterface` contains a single Container, you can still use the syntax: `multi_container_interface[None]` or `multi_container_interface.get_method_name()` to access that single container.

We could revert the bugfix since users may have relied on it working. At the very least, I will add it to the release notes of v1.4.0. 
@oruebel @ajtritt @bendichter what do you think?

**Comment by ajtritt** [comment]
> We could revert the bugfix since users may have relied on it working. 

I vote against this.

**Comment by chriski777** [comment]
Got it, thanks a bunch @rly! We'll merge your PR into suite2p as soon as the tests pass.
