### ISSUE TITLE
Bump pynwb version to 2.0 to reflect breaking change in hdmf

### ISSUE THREAD

**Issue by wbwakeman** [NeurodataWithoutBorders/pynwb#1285]
The HDMF package recently implemented breaking changes which were reflected by the version being increased to 2.0.  Since the PyNWB package is tightly integrated with HDMF, this is essentially a breaking change to PyNWB too.  This should be reflected by increasing the major version value of PyNWB to 2.0 also.

**Comment by t-b** [comment]
In which regard has hdmf breaking changes? Only API or schema level (aka on-disc format) as well?

**Comment by oruebel** [comment]
@t-b HDMF changes affect the API only. The on-disc format has not changed. 

When we did the release, we did not do a major bump for PyNWB because HDMF are primarily "under-the-hood" changes for PyNWB users, rather than front-end changes. 

As far as I understand it, the issue is that the allensdk pins both HDMF and PyNWB versions. Ideally, I think it would be best if the allensdk would only specify PyNWB as a requirement so that pip/conda can install the HDMF it needs. Would that be possible to do? If that is not an option then we could do another release with a major version bump if necessary.

**Comment by wbwakeman** [comment]
@oruebel Thanks for the response.  I will look into that possibility today

**Comment by rly** [comment]
I agree with @oruebel 's comments above.

For reference, more details about the failure case here: https://github.com/AllenInstitute/AllenSDK/issues/1689

**Comment by wbwakeman** [comment]
Will address this in requirements.txt of ipfx and allensdk

**Comment by njmei** [comment]
@rly @oruebel It looks like there is an explicit import of `hdmf` in AllenSDK.

https://github.com/AllenInstitute/AllenSDK/blob/5200c742645434c9a56518bda729b50238ee85f4/allensdk/brain_observatory/ecephys/write_nwb/__main__.py#L13

Wanted to double check with the pynwb/hdmf team that changing:

https://github.com/AllenInstitute/AllenSDK/blob/5200c742645434c9a56518bda729b50238ee85f4/allensdk/brain_observatory/ecephys/write_nwb/__main__.py#L680-L681

to:

```
        data=lfp_data,
        timestamps=lfp_timestamps,
```

Should allow us to remove that import (and remove hdmf from requirements.txt)?

Many thanks for your help!

**Comment by oruebel** [comment]
@njmei yes, that will remove the dependency but would also mean that the data would no longer be compressed. @rly I think it would be simplest if we imported H5DataIO in PyNWB main __init__.py so that users can access it directly from PyNWB without having to import it from HDMF. @njmei with regard to the gzip compression, in my experience using the maximum compression level of ``compression_opts=9``often does not yield much in data reduction compared to a medium level of 4 or 5 but at the same time can slow-down read/write. Unless you are seeing significant improvements in data size reduction by using a compression level of 9, I would suggest to relax it to 4 or 5 .

**Comment by njmei** [comment]
@oruebel Many thanks for the feedback! I'm also unsure why a compression level of 9 was used, but will investigate whether it is necessary. Let me know when `H5DataIO` can be imported from pynwb!

**Comment by oruebel** [comment]
@njmei BTW, in the meantime, since HDMF will always be installed with PyNWB, it should still be fine for you to import HDMF classes in the AllenSDK without having to list HDMF as a requirement (i.e., just listing PyNWB should be sufficient).
