### ISSUE TITLE
Encountering errors when running AllenSDK tests with pynwb 1.4.0

### ISSUE THREAD

**Issue by njmei** [NeurodataWithoutBorders/pynwb#1290]
## Description
As a part of resolving: https://github.com/NeurodataWithoutBorders/pynwb/issues/1285
I removed the `hdmf` dependency in AllenSDK `requirements.txt` and also tried running tests with the latest version of pynwb < 2.0.0.

Looks like the newest version of pynwb doesn't like something about how we're trying to access current source density (CSD) information:
https://github.com/AllenInstitute/AllenSDK/blob/7e60bc5a811f76750d22a507f449621a0784e6bd/allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb_session_api.py#L347

But the error doesn't seem terribly helpful (at least to me).
```
E               KeyError: "'current_source_density' not found in ProcessingModule 'current_source_density'."
```

## Steps to Reproduce
In a clean environment install AllenSDK with latest `hdmf` and `pynwb` and try to run tests with:

`pytest ./allensdk/test/brain_observatory/ecephys/test_write_nwb.py`

## Environment
    Python Executable: Conda
    Python Version: Python 3.6/3.7
    Operating System: Linux, Windows, and Mac
    HDMF Version: 2.2.0

## Checklist
- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
@njmei There was a bug in previous versions of PyNWB and HDMF where if `__getitem__` is called on a `MultiContainerInterface` object such as a `ProcessingModule`, then if there is only one item in the `MultiContainerInterface`, then you could use any key between the square brackets to get that item. This was fixed in the latest PyNWB so that you now have to use the name of the item as the key to get that item. Otherwise, a KeyError is raised, like for a normal dict.

i.e., the item in your `ProcessingModule` is named something besides `'current_source_density'`. Based on https://github.com/AllenInstitute/AllenSDK/blob/7e60bc5a811f76750d22a507f449621a0784e6bd/allensdk/brain_observatory/ecephys/write_nwb/__main__.py#L729-L748 it looks like it might be named `'ecephys_csd'`, so your code should instead say:
```python
nwb_csd = csd_mod["ecephys_csd"]
```

**Comment by njmei** [comment]
@rly Thanks for the fast response! ~~The problem I guess is that the NWB files that we've released were prior to this fix. Re-releasing new NWB files is not in the cards since it's a very involved and time consuming process...~~

Misread the response! I will try with the 'proper' key and see how this goes.

**Comment by njmei** [comment]
@rly Thanks, looks like that worked! I'll close this issue then.
