### ISSUE TITLE
problem validating bool

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1298]
Running validation on the Neuropixel file found [here](https://girder.dandiarchive.org/api/v1/item/5eda859399f25d97bd27985d/download) reveals an issue with the validator when validating a boolean value. It appears there is a confusion between `bool` and `bool_`.

```bash
$ python -m pynwb.validate /Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb
Validating /Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb against cached namespace information using namespace ndx-aibs-ecephys.
 - found the following errors:
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeA.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeB.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeC.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeD.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeE.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeF.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
```

**Comment by dsleiter** [comment]
@bendichter I looked into this, and here's what I believe is going on:

1. the spec for `EcephysElectrodeGroup` has a dtype of `bool` for attribute `has_lfp_data`
    > ```{'name': 'has_lfp_data', 'doc': 'Indicates availability of LFP data', 'dtype': 'bool'}```
1. the type of the value for `has_lfp_data` in this file is `np.bool_`
1. it looks to me like `ObjectMapper` always converts `bool` to `np.bool_` when writing to the file (is this correct?)
1. In addition, the user could have explicitly passed in an `np.bool_` when creating the `EcephysElectrodeGroup` object because `docval` explicitly allows `np.bool_` to pass validation when the type is specified as `bool`
    ```python
    def __is_bool(value):
        return isinstance(value, bool) or isinstance(value, np.bool_)
    ```
1. however, `hdmf.validate.validator` does not allow `np.bool_` to pass validation when the dtype in the spec is `bool`

It seems like the solution here should be to update the validator in `hdmf.validate.validator` to allow `np.bool_` as a valid dtype when the spec defines the dtype as `bool`, do you agree? If so, I'll add the issue to hdmf and work on a PR.

**Comment by bendichter** [comment]
@dsleiter thanks for tracking this down. I agree, it sounds like allowing `np.bool_` to count as a `bool` in `hdmf.validate.validator` would fix the problem.

**Comment by dsleiter** [comment]
A fix for this has been implemented here: https://github.com/hdmf-dev/hdmf/pull/505 , and should be available as of the next `hdmf` version (currently planned to be `2.4.0`).
