### ISSUE TITLE
TimeSeries unit attribute present, but a MissingRequired warning is thrown.

### ISSUE THREAD

**Issue by colleenjg** [NeurodataWithoutBorders/pynwb#1302]
## Description

When an NWB file object includes a TimeSeries with a non-accepted unit as an attribute (non SI units), 
at the moment of writing the NWB file object to a file, the following warning is thrown:
`/home/user/anaconda3/envs/nwb/lib/python3.6/site-packages/hdmf/build/objectmapper.py:695: MissingRequiredWarning: attribute 'unit' for 'data' (TimeSeries)
  warnings.warn(msg, MissingRequiredWarning)`

## Bug
1) The warning is incorrect. The unit attribute is actually present in the object, and it is **present in the NWB file that is written**. The correct warning would be that the unit is **not an accepted value, i.e. a SI unit.**
2) The requirement to use SI units seems fairly constraining here. What is recommended for a complex unit like dF/F (change in fluorescence)? Note that I tried **a.u.** and **au**, and got the same warning.

## Steps to Reproduce
```
# create response series with unit "Normalized fluorescence (A.U.)
roi_response_series = RoiResponseSeries(
    unit="Normalized fluorescence (A.U.)",
    data=np.random.rand(120 * 20).reshape(120, 20),
    timestamps=np.arange(120),
    name="test_series",
    rois=plane_segmentation.create_roi_table_region(
        description="segmented cells with cell_specimen_ids"),
 )
# add series
dff_interface.add_roi_response_series(roi_response_series)

# write NWB file
```

## Environment

    Python Executable: Conda
    Python Version: Python 3.6
    Operating System: Linux
    HDMF Version: pynwb 1.2.1

**Comment by rly** [comment]
Hi @colleenjg . Currently, PyNWB does not validate what value you enter for the `unit` attribute of a `TimeSeries` class, so providing a non-SI unit is accepted. However, a value should be supplied. In your example, the `RoiResponseSeries` has a `unit` attribute, so the warning is not coming from that object. I suspect there is another `TimeSeries` class or subclass that is missing the `unit` attribute. 

PyNWB will soon require users to supply a `unit` when it is required by the NWB schema. Not requiring it is a bug and will be fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/1274 .

**Comment by colleenjg** [comment]
Hi @rly, I see - you're correct. I thought I'd tested for this, but it seems I wasn't thorough.
