### ISSUE TITLE
6 tests fail with `FileNotFoundError` on `2.0.0_p0`

### ISSUE THREAD

**Issue by TheChymera** [NeurodataWithoutBorders/pynwb#1425]
Thanks for having addressed the previous network issue (reported [here](https://github.com/NeurodataWithoutBorders/pynwb/issues/1412)).
Unfortunately, in the mean time, 6 other tests started failing, and I'm not entirely sure why.
This is the [full build and test log](https://ppb.chymera.eu/f2564d.log), and below is the summary:

```
FAILED tests/validation/test_validate.py::TestValidateScript::test_validate_file_cached - FileNotFoundError: [Errno 2] No such file or di...
FAILED tests/validation/test_validate.py::TestValidateScript::test_validate_file_cached_bad_ns - FileNotFoundError: [Errno 2] No such fil...
FAILED tests/validation/test_validate.py::TestValidateScript::test_validate_file_cached_hdmf_common - FileNotFoundError: [Errno 2] No suc...
FAILED tests/validation/test_validate.py::TestValidateScript::test_validate_file_cached_ignore - FileNotFoundError: [Errno 2] No such fil...
FAILED tests/validation/test_validate.py::TestValidateScript::test_validate_file_no_cache - FileNotFoundError: [Errno 2] No such file or ...
FAILED tests/validation/test_validate.py::TestValidateScript::test_validate_file_no_cache_bad_ns - FileNotFoundError: [Errno 2] No such f...
```

**Comment by oruebel** [comment]
I think this is likely a different problem, since the files for these tests are not being downloaded from DANDI but are actually included in the PyNWB repo itself here https://github.com/NeurodataWithoutBorders/pynwb/tree/dev/tests/back_compat. However, these tests use relative paths when calling the validator, e.g,. ``"python -m pynwb.validate tests/back_compat/1.1.2_nwbfile.nwb"``, i.e., I believe the tests assume that the current directory is the root directory of PyNWB. Can you please check to make sure the folder ``tests/back_compat/`` validation test files exists. Also, how are you calling the test suite? Is it possible that the working directory is no the PyNWB root directory when you are running the tests?

**Comment by TheChymera** [comment]
No longer happening.
