### ISSUE TITLE
[Documentation]: Icephys tutorial output is confusing

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1467]
### What would you like changed or added to the documentation and why?

In the icephys tutorial on readthedocs, the output of `icephys_meta_df.iloc[[0, 1, 18, 19]].transpose()` does not look right, but maybe I am misreading it.

https://pynwb.readthedocs.io/en/stable/tutorials/domain/plot_icephys_pandas.html#sphx-glr-tutorials-domain-plot-icephys-pandas-py

![image](https://user-images.githubusercontent.com/310197/166300688-007baebb-0d24-44d1-a5f1-13678086eefb.png)

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
Can you clarify what seems to be wrong with the table?  As far as I can tell the table looks correct to me. 

As mentioned in the comment, the table is shown transposed to fit within the readthedocs layout, and maybe it just looks a bit strange with the multi-index on the columns. The table without transposing it would look as follows:

![Screen Shot 2022-05-02 at 3 07 42 PM](https://user-images.githubusercontent.com/10999845/166335311-55979ef1-9c06-49e8-b9c0-d7ad12eb72cd.png)

Or we can also resolve the MultiIndex by calling ``.reset_index`` on the table so that the MultiIndex becomes part of the table, which would render as follows:

![Screen Shot 2022-05-02 at 3 12 07 PM](https://user-images.githubusercontent.com/10999845/166335684-123463e6-0924-4b10-870a-df965ed33a2a.png)

**Comment by rly** [comment]
It definitely looks strange and unintuitive when transposed in the way that it is. Especially with the row shading.

Can we just show an image of the non-transposed table, kind of like what we see here on this GitHub issue, where the viewer can click the image to see it in full width? The table text does not need to be selectable. The downside is that if the code changes, the image of the table needs to be re-generated; we would have to keep them in sync... not ideal but I think it would be better than the current version.

**Comment by oruebel** [comment]
We could potentially also use https://pypi.org/project/dataframe-image/ to render the table as PNG directly from the notebook
