### ISSUE TITLE
[Feature]: Rapid iterative reads of short windows of multi-channel spikes

### ISSUE THREAD

**Issue by cboulay** [NeurodataWithoutBorders/pynwb#1485]
### What would you like to see added to PyNWB?

Using a DANDI dataset (000121) with a "Units" table, I would like to very quickly retrieve only the spike times that occurred within a specified short time window. The current method of (i) opening the file, (ii) iterating over each channel, and (iii) grabbing ALL spike times and (iv) keeping those that meet some criteria is too slow.

### Is your feature request related to a problem?

I am trying to use Ray to simulate online processing of Utah Array data. Toward this effort, I am trying to create a Ray Dataset from DANDI NWB files so they are suitable for [pipelining](https://docs.ray.io/en/latest/data/advanced-pipelines.html#enabling-pipelining).

Note: the worker that yields a time-restricted window of data (spike times, lfps, behaviour) can only receive as inputs picklable objects. This means that h5-derived types cannot be passed. I am currently passing the file name and time window to the worker. The worker opens the file, selects a small window (~2 seconds of 20-msec bins) of each of my desired data types, then yields a `ReadTask`. As you can imagine, the outlined process is too slow to be practical.

I'm trying to speed this up. For now I'm plugging my ears and covering my eyes to suggestions that the file opening is my bottleneck, and I'm trying to optimize data access once the file is opened. Maybe this is silly and I should convert from NWB to a Ray-friendly format.

### What solution would you like?

Currently, LFPs can be sliced easily:

`lfp = series.data[int(t_start * series.rate):int(t_stop * series.rate)]`

I would like to be able to do something similar for spikes. I have created a `scipy.sparse.csr_matrix` from my spike times and can slice it easily, as above for LFPs, but I don't know how to store the CSR matrix in the NWB file. CSR matrices have some limitations, e.g. they are not JSON-serializable (but they ARE picklable), so they might not be the correct container.

I looked at AbstractDataChunkIterator but I fail to see how that can be used here.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by cboulay** [comment]
Just to be a bit more explicit about the problem: If I try to create an ElectricalSeries with a sparse matrix ...

`sparse_series = ElectricalSeries(name='SparseSpikes', data=sparse_mat, starting_time=0., rate=1000.)`

... I'm met with the following error:

```
TypeError: ElectricalSeries.__init__: incorrect type for 'data' (got 'csr_matrix', expected 'ndarray, list, tuple, Dataset, Array, StrDataset, HDMFDataset, AbstractDataChunkIterator, DataIO or TimeSeries'), missing argument 'electrodes'
```

**Comment by oruebel** [comment]
> The current method of (i) opening the file, (ii) iterating over each channel, and (iii) grabbing ALL spike times and (iv) keeping those that meet some criteria is too slow.

Looking at the order of operations, one issue may be that your code may be doing a lot of small I/O requests by reading spike times from the Units table one row at a time. If you need all spike times, I would suggest simply loading the full column via something like ``spiketimes = nwbfile.units['spike_times'][:]`` first. In this way, iterating over the elements should be faster since the data is already in memory. Since the ``spike_times`` column is ragged , loading the column will I believe return a list-of-lists. If iterating over the list-of-lists is not fast enough, then you could also load the spike times directly as a flat array (without resolving the VectorIndex), then do range check with numpy, and then mask the data and resolve the VectorIndex. I'm downloading a file from DANDIset 000121 right now to see if this works. It would be helpful if you could add a code-snippet or link to your code to show how you are processing the data.

> Just to be a bit more explicit about the problem: If I try to create an ElectricalSeries with a sparse matrix ...

ElectrialSeries only supports regular arrays as data. I'm not sure if a sparse matrix is really needed here, but HDMF defines a sparse matrix type https://hdmf.readthedocs.io/en/stable/hdmf.common.sparse.html?highlight=csr#hdmf.common.sparse.CSRMatrix that you may be able to use (however, this is not a TimeSeries type).

**Comment by cboulay** [comment]
Thank you for the prompt reply.

>  I would suggest simply loading the full column via something like spiketimes = nwbfile.units['spike_times'][:] first.

Unfortunately, this is exactly what I'm trying to avoid.

Perhaps I'm misunderstanding Ray but, AFAICT, the processing of the `ReadTask`s is stateless; I need to load the full column once for each ReadTask -- currently there are 2000 of them.

A more direct fix might be to load the full spike data into memory before generating the task callbacks then include it in the pickle that gets shipped to each `ReadTask`, but then I have my full spike times in memory on each node for the entire duration of the processing. This is my current plan if I can't store sliceable spikes in the NWB, except I'd pass it as a csr_matrix because that's much faster to slice.

An alternative is to not use `DatasetPipeline` at all, and use an `Actor` (stateful worker) to load the data, but I don't know how to yield chunks iteratively using this approach. I'm new to Ray so that doesn't say much.

Thanks for the tip about the HDMF CSRMatrix. I assume this means that I can then store that object _somewhere_ in the NWB. Is that correct? If I have no chance of conforming to spec anyway, where would you recommend I store it?

**Comment by cboulay** [comment]
> I assume this means that I can then store that object somewhere in the NWB. 

I'm still struggling with this. I guessed that the "scratch" data was the most permissive. It tried `nwbfile.add_sratch(CSRMatrix(...))` or even `ScratchData(CSRMatrix(...))`. The latter raises:

`TypeError: ScratchData.__init__: incorrect type for 'data' (got 'CSRMatrix', expected 'str, int, float, bytes, bool, ndarray, list, tuple, Dataset, Array, StrDataset, HDMFDataset, AbstractDataChunkIterator, DataIO or Data')`

`CSRMatrix` inherits from hdmf `Container` but sadly fails to pass any of those class tests. I even tried to create a `NWBSparse` that inherits from both CSRMatrix and NWBMixin but that also failed to pass.

I'm starting to think I should store the set of arrays that underlie a CSR matrix (data, indices, indptr) and then recreate the spa.csr_matrix on demand. It's late now, but soon I'll try to time that approach incl. slicing vs a couple other approaches to get window-limited spikes.

**Comment by cboulay** [comment]
It just occurred to me that, unlike ndarrays, I can't load a sparse array lazily. Even if I manage to store the csr_matrix in the NWB file, I still have to load the whole thing into memory before I can slice it. My test-file's spikes as a sparse array occupies 80 MB (indices.nbytes + indptr.nbytes + data.nbytes) vs 127 MB for `nwbfile.units.spike_times[:].nbytes`, so there's still some benefit to this approach. If I convert the spike matrix to a dense boolean array then that is easy to store in the nwb but it will increase the file size by ~1.6 GB. But this might be worth it because then I can slice it lazily.

Thanks for letting me think out loud here.

**Comment by bendichter** [comment]
1. > For now I'm plugging my ears and covering my eyes to suggestions that the file opening is my bottleneck

This is likely a bottleneck. Opening in pynwb is rather expensive, as it parses all the groups and attributes for the entire NWB file into builder objects. A faster way would be to read via h5py, but I think the best solution might be to just pass the entire spike train matrixes `spike_times` and `spike_times_index`.

2. This Units spike_times format is built to optimize for getting all the spike times for a particular unit rather than getting all spike times for all units for a particular time window. If you want a query to return the spike times for a particular unit in a particular window, it is best to get the unit spike times first and then window them. If you want all units, unfortunately the best way will probably be to do that in a loop. `np.searchsorted` should help here. I did implemented something like this on disk [here](https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/blob/c891978d74a2e52a3ccbf65949f5b8192858e1dc/nwbwidgets/utils/units.py#L8-L29) but in retrospect it would have been much much faster for me to just read the spike data for a particular unit into a numpy array and use `np.searchsorted`. If you think the size of the spike arrays are reasonable for your RAM that's the path I would recommend.

**Comment by cboulay** [comment]
Thanks for the tip that `NWBHDF5IO` might be slow; I'll try with `h5py`.

I don't think I can pass my data structures as arguments to each node. I didn't mention it previously, but I'll also be slicing LFPs, behavioural data (cursor position), and trial events. This adds quite a bit of bloat to my serialized data blob that I'd be transmitting to each node and then residing in RAM. I'll keep toiling away at the lazy-loading.

I guess this issue can be closed. Though I'd like to advocate one more time to support for storing a CSRMatrix (and CSCMatrix if it existed in hdmf) in a Series `.data`. They are very useful containers.
