### ISSUE TITLE
Add ontology support

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#15]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

Spec objects should support adding ontology and ontology id

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/15

**Comment by oruebel** [comment]
Related issues:

- NWB Schema: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/1
- PyNWB issue with discussion from previous hackathon: https://github.com/NeurodataWithoutBorders/pynwb/issues/513
- Related use case: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/477

A solution for this is currently being developed in HDMF:
- https://hdmf.readthedocs.io/en/stable/tutorials/External_Resources.html#sphx-glr-tutorials-external-resources-py

**Comment by bendichter** [comment]
@rly , @oruebel I'm thinking about creating a tutorial in PyNWB to illustrate best practices in using ndx-external-resources. What do you think?

**Comment by rly** [comment]
There are still questions about whether the HERD data is integrated within the NWB file or outside the NWB file before upload to DANDI though. Otherwise, HERD is pretty much done. See https://hdmf.readthedocs.io/en/stable/tutorials/plot_external_resources.html . 

A tutorial in PyNWB would be a good idea. @mavaylon1 is working on https://github.com/NeurodataWithoutBorders/pynwb/pull/1781
