### ISSUE TITLE
[Feature]: `ImageSeries`: check `starting_frame` when `external_file` is used

### ISSUE THREAD

**Issue by weiglszonja** [NeurodataWithoutBorders/pynwb#1510]
### What would you like to see added to PyNWB?

Related to #1318 and #1470, when  `external_file` is used in `ImageSeries` a new check should be added which ensures that
a) `starting_frame` is provided if `external_file` `is` used,
b) `starting_frame` has the same length as `external_file`. 

Currently `starting_frame` is set to `[0]` by default, which is fine for a single external file but is incorrect for multiple external files. 

### What solution would you like?

A new check method in  ImageSeries.__init__ that checks if
a) `starting_frame` is provided if external_file is used
b) `starting_frame` has the same length as external_file. 

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by weiglszonja** [comment]
Actually, there is a default value of `[0]` for `starting_frame`:
https://github.com/NeurodataWithoutBorders/pynwb/blob/6505d8631169befe9225e472788c8a8d9f5e0af3/src/pynwb/image.py#L46-L49
that gets overwritten when external file is not used:
https://github.com/NeurodataWithoutBorders/pynwb/blob/6505d8631169befe9225e472788c8a8d9f5e0af3/src/pynwb/image.py#L77-L78

therefore a) is silently taken care of. do you think @oruebel this should be changed? 
the second warning would get triggered with the default value as well if it doesn't match the length of `external_file`, I was just wondering if this logic should be changed.

**Comment by oruebel** [comment]
> do you think @oruebel this should be changed?

In principle I think it should be sufficient in this case to just add the check to enforce that ``starting_frame`` has the same length as ``external_file``. 

On a separate note though, from a user perspective, I find this current behavior a bit confusing. I would have expected the behavior to be reversed. I.e.:

1.  Have the default value for ``starting_frame`` as ``None``
2. Set ``starting_frame`` to ``[0,]`` in ``__init__`` if ``external_file`` has length 1

The end result of this is ultimately the same as the current behavior, so this is not critical. However, I find it strange that the default value of ``starting_frame`` reflects the very specific case of ``external_file`` with a single file, rather than the more general case of ``data`` being provided. I just think from a documentation perspective, having the default value of ``starting_frame`` be ``None`` would be more intuitive. What do you think?

**Comment by weiglszonja** [comment]
I completely agree, I would change it to `None` as well.

**Comment by oruebel** [comment]
> I completely agree, I would change it to `None` as well.

Sounds good. In this case, I would suggest we:

1. Add the check to ensure that ``starting_frame`` has the same length as ``external_file``
2. Change the default value for ``starting_frame`` to ``None`` 
3. Set ``starting_frame`` to ``[0,]`` in ``__init__`` if ``external_file`` has length ``1``

Item (3) is mainly for backwards compatibility as it ensures that the behavior of the API doesn't change in case that a user provides a single ``external_file``, thus, avoiding a breaking change and allowing us to include this change in a minor or bugfix release, rather than requiring a major version bump.
