### ISSUE TITLE
[Documentation]: Tutorials not following best practices specified by the NWBInspector

### ISSUE THREAD

**Issue by emilyasterjones** [NeurodataWithoutBorders/pynwb#1628]
### What would you like changed or added to the documentation and why?

Tutorial documentation does not follow the Best Practices specified by NWBInspector. For instance, [the ecephys tutorial](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/gallery/domain/ecephys.py) begins by specifying an experimenter ('Dr. Bilbo Baggins') that doesn't match [best practices convention](https://nwbinspector.readthedocs.io/en/dev/best_practices/nwbfile_metadata.html#file-metadata) ('Baggins, Bilbo') .

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
@emilyasterjones  thanks for the helpful issue. Many of the tutorials were created before the NWBInspector existed and I absolutely agree that they should be updated accordingly. To help us find these issues and help ensure that tutorials keep up with best practices I would suggest the following:

1. Enhance the test suite for the tutorials to run the NWBInspector on all files created by the tutorials. One approach for this would be to either: a) define a standard pattern for where files created by tutorials are placed so that we can run the inspector on those files and/or b) add calls to the NWBInspector in the tutorials itself. I think we probably want to do (b) at least for some tutorials as well to show running the NWBInspector as a best practice
2. Once we know which tutorials have issues, we can then go through and fix those issues.

**Comment by oruebel** [comment]
@CodyCBakerPhD @mavaylon1 do you think you could help with adding NWBInspector tests for the tutorials. I think the most critical ones would the [Domain Specific Tutorials](https://pynwb.readthedocs.io/en/stable/tutorials/index.html#domain-specific-tutorials)
