### ISSUE TITLE
How to pass dynamic filters compression options to `H5DataIO`?

### ISSUE THREAD

**Issue by h-mayorquin** [NeurodataWithoutBorders/pynwb#1629]
The obvious way to me would be to do something like:

```python
import hdf5plugin
from hdmf.backends.hdf5.h5_utils import H5DataIO
import numpy as np

data = np.random.rand(10, 2)
data.shape

plug_in = hdf5plugin.BZip2()
filter_id = plug_in.filter_id
compression_opts = dict(blocksize=7)
wrapped_data = H5DataIO(data=data, compression=filter_id, allow_plugin_filters=True, compression_opts=compression_opts)
```
However, because [H5DataIO](https://hdmf.readthedocs.io/en/stable/hdmf.backends.hdf5.h5_utils.html#hdmf.backends.hdf5.h5_utils.H5DataIO) expects either an int or a tuple for the `conversion_opts` this throws an assertion:

```python
TypeError: H5DataIO.__init__: incorrect type for 'compression_opts' (got 'dict', expected 'int or tuple')
```

I guess that the final goal is to store this into `__iosettings`, so this is properly mapped when `create_dataset` is called at the moment of writting. From that perspective, maybe this can be done by only adding dict as a possible type on `conversion_opts`?

**Comment by oruebel** [comment]
The ``compression`` and ``compression_opts`` should match what ``h5py.create_dataset`` allows as inputs. If ``dict`` is supported for ``compression_opts`` in h5py then we could add it to H5DataIO, but if I remember correctly h5py expects an int or tuple here. 

However, hdf5plugin (at least in the latest version) supports unpacking of the filters via ``**`` to produce the parameter settings that h5py expects. I.e., instead of setting ``compression`` and ``compression_opts`` yourself, you can just use `` **hdf5plugin.BZip2(blocksize=7)`` to set the options. I.e., with this your example would look as follows:

```
import hdf5plugin
from hdmf.backends.hdf5.h5_utils import H5DataIO
import numpy as np

data = np.random.rand(10, 2)
wrapped_data = H5DataIO(data=data, allow_plugin_filters=True, **hdf5plugin.BZip2(blocksize=7))
```

This seems to be the recommended usage pattern for hdf5plugin and I think helps simplify the code.

**Comment by h-mayorquin** [comment]
Thanks, so the h5py expects the `compression_opts` on a tuple and `dict(pluging)` is built in such a way that the tuple is formated in the correct way:

```python
dict(hdf5plugin.Blosc(cname='lz4', clevel=5, shuffle=1))
{'compression': 32001, 'compression_opts': (0, 0, 0, 0, 5, 1, 1)}
``` 

Thanks for the explanation, I could not extract this from the documentation of h5py or the pulgings (altought I saw the unpacking **operator example before).

> This seems to be the recommended usage pattern for hdf5plugin and I think helps simplify the code.

I think it goes against the "explicit is better tha implicit" injuction but it does make the code more concise / shorter I guess.
