### ISSUE TITLE
Reconsider usage of scipy

### ISSUE THREAD

**Issue by dorukozturk** [NeurodataWithoutBorders/pynwb#168]
From what I can tell it is only used here https://github.com/NeurodataWithoutBorders/pynwb/blob/17699d46b6bc3902b8fa47fb24f4f376b1b7ddc0/tests/build_fake_data.py#L58
Can we replace that line without bringing scipy and all of it's dependencies?

**Comment by neuromusic** [comment]
`spatial_data = np.cumsum(np.random.normal(size=(2,len(spatial_timestamps))), axis=-1).T`

**Comment by nicain** [comment]
I have always stayed away from random number generation in unit tests, because if it does pop, you don't know how to reporoduce the state that caused the error.  IMO At the very least we should use numpy and seed with a known seed to generate consistent testing values, that can be recapitulated in case the test fails and needs to be debugged

**Comment by nicain** [comment]
2 hour ticket closure, damn good work team!  Way to go CI/CD :)
