### ISSUE TITLE
Drop 3.7?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1712]
### What happened?

Python 3.7 on macs is failing CI. Something to do with compiling compression algorithms. Python 3.7 officially drops support in 3 days, so I vote we just remove support for 3.7 and don't worry about fixing it.

### Steps to Reproduce
See CI: https://github.com/NeurodataWithoutBorders/pynwb/actions/runs/5384927945/jobs/9773407167?pr=1707

### Operating System

macOS

### Python Executable

Python

### Python Version

3.7

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
Python 3.7 has end of life today: https://endoflife.date/python so let's start moving on this issue to reduce our maintenance and CI load, especially because the major scientific python libraries have already dropped 3.7 support and we will probably start running into compatibility issues in order to capture the latest bug fixes

**Comment by bendichter** [comment]
ah, I stand corrected, the eol is indeed today!
