### ISSUE TITLE
[Documentation]: strange indexing of tutorials

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1726]
### What would you like changed or added to the documentation and why?

<img width="311" alt="image" src="https://github.com/NeurodataWithoutBorders/pynwb/assets/844306/383e9024-7633-4535-beab-ef86c0745fc3">

@oruebel do you know how this is generated?

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
I triggered a rebuild of the docs on RTD just in case, but (not surprisingly) that did not fix the issue. Strangely, when I build the docs locally the index looks fine. 

![Screen Shot 2023-07-19 at 11 52 57 AM](https://github.com/NeurodataWithoutBorders/pynwb/assets/10999845/80373a1c-6676-4b27-8e76-c5feb5f7d3dc)

My guess is that maybe something has changed in sphinx-gallery and that RTD is using a different version than what I have installed locally. In terms of code, my initial guess is that this probably due to the customization we do to sort the tutorials within each section, which is here:

https://github.com/NeurodataWithoutBorders/pynwb/blob/d40dd30220e798d34a8fb0b6186771dba477cfd5/docs/source/conf.py#L63-L137

The quick fix would be to simply not show the [+] for the tutorials by reducing the depth of the index.

**Comment by oruebel** [comment]
Ok, I just upgraded my local version of sphinx_gallery from 10.x to the latest version 13 and am seeing the same issue, i.e., this appears to be a bug in sphinx_gallery or some breaking change in the API that requires updates in our code.

**Comment by oruebel** [comment]
Ok, I tried with sphinx-gallery v 0.13, 0.12.2, 0.11.1, and 0.10.1. 0.10.1 works correctly and all the newer versions show the same issue, i.e., it looks something broke in 0.11. As an immediate fix, I think we can just pin the version of spinx-gallery and then investigate further whether this is something that requires a fix in sphinx-gallery or on our end.

**Comment by oruebel** [comment]
#1728 addresses this issue by fixing the version of sphinx-gallery to 0.10.1.

I also filed an issue ticket on the sphinx-gallery repo https://github.com/sphinx-gallery/sphinx-gallery/issues/1152 . Looking at the changelog for sphinx-gallery 0.11.0 it looks like they fixed a very similar issue in that release  https://github.com/sphinx-gallery/sphinx-gallery/issues/935 . Maybe that fix did not cover our case.
