### ISSUE TITLE
Disabling direct push on dev branch

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#174]
All contributions should go through the "PR-CI-Integrate" cycle.

If CI doesn't make sense for a given commit (e.g typo in a License file, ...), it could be skipped adding the comment `[ci skip]`.

Cc: @dorukozturk @mgrauer @oruebel

**Comment by dorukozturk** [comment]
I suggest we make dev as a protected branch like specified [here](https://github.com/blog/2051-protected-branches-and-required-status-checks). I can set this up if there are no objections.

**Comment by ajtritt** [comment]
This has been the policy since the beginning. dev is protected, and @oruebel and myself are the only ones that can override CI checks by exercising admin privileges.

**Comment by dorukozturk** [comment]
@ajtritt my bad, I should have been more clear. I saw that dev is already a protected branch. The thing we propose is: we only change dev through pull requests where all the tests pass on all CIs. If we activate status checks on the repo for dev branch, even if we are admins, unless the tests are passing we won't be able to merge. This will ensure dev is always stable and reliable, since we will be cutting releases off of dev.

**Comment by ajtritt** [comment]
Got it. That sounds reasonable to me. Does this make reviewers obsolete then?

**Comment by dorukozturk** [comment]
No, still reviewer's approval will be required.
