### ISSUE TITLE
[Bug]: `TypeError: `dumps_kwargs` keyword arguments are no longer supported.` when running tests on pynwb 2.5.0

### ISSUE THREAD

**Issue by TheChymera** [NeurodataWithoutBorders/pynwb#1799]
### What happened?

Full build log including tests: https://ppb.chymera.eu/345788.log

### Steps to Reproduce

```python
python3.11 -m pytest -vv -ra -l -Wdefault --color=yes -o console_output_style=count -p no:cov -p no:flake8 -p no:flakes -p no:pylint -p no:markdown -p no:sugar -p no:xvfb -p no:pytest-describe -p no:plus -p no:tavern --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_cached --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_cached_bad_ns --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_cached_core --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_cached_extension --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_cached_extension_pass_ns --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_cached_hdmf_common --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_cached_ignore --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_invalid --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_list_namespaces_core --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_list_namespaces_extension --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_no_cache --deselect tests/validation/test_validate.py::TestValidateCLI::test_validate_file_no_cache_bad_ns
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.11

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
Thanks for sharing the log. As far as I can tell from the log, this looks like an error in the DANDIAPI related to the use of pydantic. From a quick google search, it looks `pydantic` removed in version 2 the option to pass custom options to json dumps https://stackoverflow.com/questions/77076597/is-it-possible-to-get-pydantic-v2-to-dump-json-with-sorted-keys 

PyNWB does not have `pydantic` as a dependency, so this gets probably installed via the `dandi` python package. I don't think this is an issue we can fix in PyNWB, but is something that I think will need to be fixed in `dandi`. A possible workaround may be to install  `v1.10.13` of `pydantic. 

I would recommend creating an issue on https://github.com/dandi/dandi-cli for this.

**Comment by oruebel** [comment]
Actually, I think the issue may be https://github.com/dandi/dandi-schema instead

**Comment by oruebel** [comment]
Looking at the requirements for `dandi-schema`, it actually requires `pydantic[email] >= 1.8.1, < 2.0` (see
https://github.com/dandi/dandi-schema/blob/36753193205198b7855aed842af76d5e5829816f/setup.cfg#L33). I.e., it looks like the only solution is to either downgrade `pydantic` to version `1.10x.` or to update `dandi-schema` to support `pydantic >2.0`. 

It looks like there is already an open issue for this here https://github.com/dandi/dandi-schema/issues/176 . I'll close this issue for now here, since we can't fix this on our end, and leave a note about this issue there.

**Comment by TheChymera** [comment]
Thank you for the clarification!
