### ISSUE TITLE
[Bug]: Docs not rendering up to date version?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/pynwb#1833]
### What happened?

Was looking for remfile tutorial in the docs: https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html#sphx-glr-tutorials-advanced-io-streaming-py

Which I thought should have been there following https://github.com/NeurodataWithoutBorders/pynwb/pull/1761/files

### Steps to Reproduce

```python
https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html#sphx-glr-tutorials-advanced-io-streaming-py
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

lower version (unsupported)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
I think this is because that part was added after the last release of PyNWB so it is only on the `dev` version of the docs but not yet the `stable` version. It should appear once a new release for PyNWB has happened. The remfile tutorial shows up in the `dev` version of the docs here  https://pynwb.readthedocs.io/en/dev/tutorials/advanced_io/streaming.html#method-3-remfile
