### ISSUE TITLE
Additional flexibility within electrode_table

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#194]
As it is currently defined, electrode table requires a unique ID (which, I'm assuming, would be the experimenter defined electrode number), a location in the brain and various coordinates.  This is fine for fixed electrodes, but many experiments involve electrodes that are moved across some period of time, and it would be helpful/important to be able to associate a given dataset with a specific electrode when it was at a specific position.  One way that would be reasonable to solve this from a users point of view would be to have the option of defining an epoch over which the electrode table was defined, and thus allow multiple electrode tables over time.

**Comment by oruebel** [comment]
@lfrank using the current electrode table design, I can see a couple of options here:

1. The simplest solution may be to just add a new entry (i.e., row) to the electrode table for each unique position of the electrode (while keeping the ID for the electrode the same). Since the location and other metadata of the electrode changes this approach seems reasonable. This would allow you to reference the electrode uniquely based on its position and at the same time allow you to extract all positions by looking up all electrodes with the same ID. This would work with what we have right now, i.e., based on what you described you might also want to reference an Epoch either from the ElectrodeGroup (assuming that multiple electrodes move together) or from the electrode table. 
2. Similar to what you suggested, you could also create multiple electrode tables, each being associated with an Epoch. 

Technically, I think you could test either of these approaches fairly easily right now with some simple extensions. For 1. you just need to add a link to an Epoch to the ElectrodeGroup or ElectrodeTable and. For 2. you would just need to add an attribute with a reference to an Epoch to the ElectrodeTable and add multiple electrode tables to the file. 

@ajtritt any thoughts.

**Comment by lfrank** [comment]
@oruebel Thanks, those are both great suggestions.  I prefer #1 for simplicity and flexibility, and we can work on creating that extension with additional epoch information for each entry in the electrode table.

**Comment by lfrank** [comment]
One additional comment: This is also related to issue 3 in the nwb-schema repo.

**Comment by lfrank** [comment]
@oruebel @ajtritt Oliver and Andrew - when you have time:

It is not clear to me how to define an extension that includes a link to an Epoch.  I've tried various things, including 

> FL_ElectrodeGroup_ext = NWBGroupSpec('Frank Lab Electrode Group',
								 groups=[NWBGroupSpec('time range over which this electrode group is defined',
													  'valid_times',
													  default_name=None,
													  groups=[],
													  datasets=[],
													  attributes=[],
													  links=[],
													  linkable=True,
													  quantity=1,
													  neurodata_type_def=None,
													  neurodata_type_inc='Epoch')],
								 neurodata_type_inc='ElectrodeGroup',
								 neurodata_type_def='FL_ElectrodeGroup')

> 

but when I then do

help(FL_ElectrodeGroup) 

it lists |      Args:
 |          name (str): the name of this electrode
 |          source (str): the source of the data
 |          description (str): description of this electrode group
 |          location (str): description of location of this electrode group
 |          device (Device): the device that was used to record from this electrode group
 |          valid_times (list or tuple or dict or set): time range over which this electrode group is defined
 |          parent (NWBContainer): The parent NWBContainer for this NWBContainer

Which doesn't seem to suggest that valid_times is an Epoch.

any suggestions would be welcome.

**Comment by lfrank** [comment]
@oruebel  Oliver - another question on this: it doesn't seem to be possible to create a custom electrode table extension that might allow for additional fields, presumably because it is not an NWBContainer.  Is that right?

**Comment by rly** [comment]
@lfrank I think supporting electrodes at different locations within a session can be done now as @oruebel described using multiple groups of rows of the electrodes table with different locations and linking them to different ElectricalSeries objects, epochs, and trials. Please reopen this issue if that is not sufficient.
