### ISSUE TITLE
ability to specify conditions under which certain datasets/attributes are present

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#22]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

Examples
* TimeSeries.timestamps or TimeSeries.starting_time present, but not both
* control and control_description must both be present

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/22

**Comment by ajtritt** [comment]
*Original comment by* **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**:

----------------------------------------

In the previous version of the NWB specification language this was implemented by the ```_required```.

**Comment by oruebel** [comment]
CC @nclack since this issue came up during discussion of MatNWB.

It might make sense to describe these conditions that relate to the quantity of datasets/groups directly as part of the ``quantity`` flag. Currently the ``quantity`` flag is just a single value, but it could potentially be a list, where each value has a condition. For example, for the example of TimeSeries mentioned above, TimeSeries.timestamps could have a quantity key that could look something like:

```
quantity:
  - value: 0
    condition: starting_time
  - value : 1
    condition: None 
```

The quantity flag in this way would essentially describe a ``if elif elif else`` statement. @ajtritt what do you think?

I think we want to avoid using regular expressions as part conditions, so we may need to have some keys like: ``exists: starting_time`` etc. to describe the conditions explicitly.

**Comment by tjd2002** [comment]
As we start to build query/analysis tools we are running into this need more explicitly. 

Just as an example, for columnar TimeSeries data (like a [SpatialSeries](https://pynwb.readthedocs.io/en/stable/pynwb.behavior.html?highlight=spatial_series#pynwb.behavior.SpatialSeries)), it sure would be nice to refer to the data columns as ['pos_x'] and ['pos_y'] rather than [0] and [1]. 

Currently this ordering must be inferred from the docs for [pynwb.behavior.Position](https://pynwb.readthedocs.io/en/stable/pynwb.behavior.html?highlight=spatial_series#pynwb.behavior.Position), which read: 
"Position data, whether along the x, x/y or x/y/z axis."

```python

# Store some position (x,y) data:
pos = pynwb.behavior.Position(spatial_series=position_list, 
                              name='Position')

pos.create_spatial_series(name='Position d4', 
                              timestamps = timestamps,
                              data=my_pos_dataframe.[['x', 'y']] * m_per_pixel,
                              reference_frame='top left corner of video frame',
                              unit='m')
```

Then on read, we manually re-label the columns

```python
position_h5py = nwbf.modules['Behavior']['Position']['Position d4']
position_data = pd.DataFrame(data=position_h5py.data[()], columns=['pos_x', 'pos_y'])
```

Facilities for labeling columns already exist in hdf5 (and xarray, pandas,...), it seems it should be straightforward to implement once we decide on the right way to express things in the spec.

**Comment by rly** [comment]
This is a schema language and schema issue. I added https://github.com/hdmf-dev/hdmf-schema-language/issues/40 to document that if/when we migrate to a different schema language.
