### ISSUE TITLE
Consistent branding across project

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#281]
It would be great if the logo on the pynwb read-the-docs and nwb.org were unified.  

@cmartin-kavlifoundation How was the branding for nwb.org constructed?  Is there any way to unify across the moving parts?

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by cmartin-kavlifoundation** [comment]
@nicain Unifying the branding is a discussion that will probably involve more people than just me, but I'm happy to give it a start and see what other people think.

1) The NWB logo (on nwb.org) is something we are happy to stay with since it represents NWB as a whole with NWB:N and in turn PyNWB as important sub-projects.
2) As a first step, we would be happy to put the PyNWB logo on the nwb.org web page, but we would need someone to send us the source graphic file so we could convert it to a transparent or black background image.
3) As a side issue, I'm not sure who created the PyNWB logo, but if there was a desire to redo it, we would be happy to provide the original NWB graphic file that could be used as source material to be customized into a new PyNWB logo that would have a clearer graphical ancestry from the NWB logo.

We're open to suggestions and would welcome thoughts from anyone before we make any hasty changes.

Cheers,
   Chris

**Comment by neuromusic** [comment]
Thanks for the input Chris! Agreed that we don't need to do hasty changes... I completely agree with number 1: the NWB branding should take precedence and whatever PyNWB uses should conform to the NWB brand. As such, I'd push for dropping the current pynwb logo and either drop in the NWB logo (which should be sufficient for the pynwb documentation, etc) or develop a pynwb logo which is consistent with the NWB brand.

**Comment by nicain** [comment]
@cmartin-kavlifoundation 

> As a side issue, I'm not sure who created the PyNWB logo, but if there was a desire to redo it, we would be happy to provide the original NWB graphic file that could be used as source material to be customized into a new PyNWB logo that would have a clearer graphical ancestry from the NWB logo.

Awesome, can you please send me the graphic file to play around with? One of the members of our communications team has agreed to help out, and can make a first pass.

**Comment by nicain** [comment]
@cmartin-kavlifoundation This issue (#281) came up during our scrum today.  Can you please send me the graphic file when you have a chance?

**Comment by flygirlPhD** [comment]
Let me check with David on the status of this.

**Comment by nicain** [comment]
@flygirlPhD RE:

> Awesome, can you please send me the graphic file to play around with? One of the members of our communications team has agreed to help out, and can make a first pass. 

FYI the team member from communications I referred to here has left the Institute.

**Comment by flygirlPhD** [comment]
![nwb-logo-hi-res](https://user-images.githubusercontent.com/37299638/37301833-20d9f078-2600-11e8-8089-e169d69091de.png)

**Comment by flygirlPhD** [comment]
@nicain Let me know if that works, or if you need something different. Thanks!

**Comment by nicain** [comment]
@flygirlPhD thanks, that is great.  As of now, I don't think there is anyone with any bandwith to work on an updated logo; Ill see if we get any traction at the upcoming hackathon in April.
