### ISSUE TITLE
Clarification of extension inheritance

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#291]
Based on my experimentation, it's important that custom NWB datatypes inherent NWBContainer, as otherwise they cannot be included as links in other custom types.

It would be very helpful if that could be clarified in the documentation to indicate that
`neurodata_type_inc=NWBContainer` or some other subclass of NWBContainer should be the norm.

**Comment by oruebel** [comment]
@ajtritt can you confirm if this true? My understanding of this is as following:

- In order for data to be defined as a link in a spec it needs to have a unique type, i.e., ``neurodata_type_spec`` needs to be set. However, it does not necessarily have to inherit from ``NWBContatiner``
- Inheriting from ``neurodata_type_inc=NWBContainer`` should however be mentioned in the docs as a best practice as it potentially allows for a bit deeper integration with NWB and allows the type to inherit new features we may add the NWBContainer in the future. 
- In order to integrate a new type with the existing format, e.g., to include as part of a processing module, it will need to inherit from ``NWBContainer`` either directly or by inheriting from another NWB group type.

@ajtritt I'll assign the ticket to myself as  this is a docs issue that I can fix quickly, I just wanted to confirm that I'm not misunderstanding something here.

**Comment by ajtritt** [comment]
This has been addressed here:

https://pynwb.readthedocs.io/en/latest/building_api.html
https://pynwb.readthedocs.io/en/latest/tutorials/general/extensions.html#sphx-glr-tutorials-general-extensions-py
