### ISSUE TITLE
Request: include data field to OptogeneticStimulusSite (ogen.py)

### ISSUE THREAD

**Issue by BCJongbloets** [NeurodataWithoutBorders/pynwb#311]
Problem/Use Case:
In case of laser scanning photostimulation (in and ex vivo) the location of the photostimulation ('OptogeneticStimulusSite' in 'ogen.py') is variable (XYZ and time). At the moment there is only the field 'Location' which allows for a string input. This suffices for a fixed stimulation location only. 

To allow for description of variable locations it would be helpful to have a data field in class('OptogeneticStimulusSite' in 'ogen.py'). The data field should allow for storage of an 4 dimensional numpy array (XYZT).

Downside of this addition of the 'Data' field would be that users without variable locations need to provide a 'Data' array. I don't know if there is away to make the 'Data' field optional, hence I haven't made a version of 'ogen.py' myself?!

**Comment by neuromusic** [comment]
Hi @BCJongbloets thanks for the feedback.

Since this is a proposed change to the core NWB schema, the behavior is specified here https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.ogen.yaml#L32

I've created an issue there for discussion: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/101

I would not expect any major changes to the core schema in the near future. In the meantime, I suggest creating an extension to store the scanning location data. See: http://pynwb.readthedocs.io/en/latest/tutorials.html

**Comment by nicain** [comment]
@BCJongbloets If you make a cut at this, and have questions, I am happy to offer a little feedback and help (as time permits).

**Comment by BCJongbloets** [comment]
Great thanks @nicain @neuromusic! @mtv2101 The stimulus (in your case expressed in voltage) itself is described in "OptogeneticSeries" and can hold any given value (voltage/wattage) at user-supplied time-interval. So I don't think addition of the voltage parameter is necessary, if I understand you correctly.  

To review my request, we could/should leave out time in the "data" field (so XYZ instead of XYZT) since there is already the "timestamp" field.
