### ISSUE TITLE
`io.read()` taking >10 min

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#374]
## Bug

I have an (admittedly pretty large) file with on the order of 100 datasets. It's taking forever for `io.read()` to run and I don't know why. It's been running for 10 minutes.

You can download the data here: https://www.dropbox.com/s/4qa1pblx9xhqwrl/yuta_data.nwb?dl=0

and I'm using this code:
```python
io = NWBHDF5IO('path/to/yuta_data.nwb', 'r')
io.read()
```

**Comment by ajtritt** [comment]
Looks like it's a problem with Clustering.cluster_nums. This dataset is computed by the constructor. It's counting the number of unique values in Clustering.nums. 

This data type is another that would benefit from the same type of structure that you're using for spike trains. We should probably change this type. In the meantime, I will modify the constructor so that it doesn't need to compute this on read.
