### ISSUE TITLE
Improve test installation of wheels and source distributions

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#436]
## 1) Bug

Tox is currently testing the installation of the wheels using `recreate --installpkg`. 

https://github.com/NeurodataWithoutBorders/pynwb/blob/7a089be91fd72825f6209bcfb55b5c1cccfb82f1/.circleci/config.yml#L55-L59

The problem is that the requirements files are systematically installed and this approach currently  doesn't check the list associated with `install_requires` is correct.

https://github.com/NeurodataWithoutBorders/pynwb/blob/7a089be91fd72825f6209bcfb55b5c1cccfb82f1/setup.py#L26-L34

Indeed, the example of tox execution reported below demonstrates this:

```
$ tox -e py35 recreate --installpkg dist/*-none-any.whl
py35 recreate: /home/jcfr/Projects/pynwb/.tox/py35
py35 installdeps: -rrequirements-dev.txt, -rrequirements.txt
py35 inst: dist/pynwb-0.2.0.post0.dev558-py2.py3-none-any.whl
py35 installed: certifi==2018.1.18,chardet==3.0.4,codecov==2.0.13,configparser==3.5.0,coverage==4.4.2,enum34==1.1.6,flake8==3.5.0,h5py==2.7.1,idna==2.6,linecache2==1.0.0,mccabe==0.6.1,numpy==1.14.2,pluggy==0.6.0,py==1.5.2,pycodestyle==2.3.1,pyflakes==1.6.0,pynwb==0.2.0.post0.dev558,python-dateutil==2.7.2,requests==2.18.4,ruamel.yaml==0.15.35,six==1.11.0,tox==2.9.1,traceback2==1.4.0,unittest2==1.1.0,urllib3==1.22,virtualenv==15.1.0
py35 runtests: PYTHONHASHSEED='1358482435'
py35 runtests: commands[0] | python test.py
```

**Comment by mgrauer** [comment]
@bendichter 

We thought we were testing pip package installs, but we were testing them with requirements instead of setup.py, so that does not reflect how it would install on your system. There very well could have been a bug with the pip installation and we wouldn't have known it with the current testing.

Thanks for bringing this to our attention and we will be notified of these problems in the future by our CI once this is fixed.
