### ISSUE TITLE
Coverage patch threshold

### ISSUE THREAD

**Issue by dorukozturk** [NeurodataWithoutBorders/pynwb#461]
## Feature Request

Codecov has a feature which is used to set a coverage threshold for PRs. Here are the advantages and disadvantages for this feature:

### Pros
1) This will ensure PR's can only be merged with "some" testing. "some" is dependent on how we set up the threshold. If we set it up to 100%, that means every line that is newly added needs to be covered before getting merged. I recommend setting it to something like 80% just to make sure we maintain a high quality in our PRs.
2) If a feature is added or bug fixed and there are tests associated with the feature/bug fix, it is much more easier to reason about the PR for the reviewer. 
3) This will ensure we don't drop our coverage significantly while implementing new features. 
### Cons
1) WE HAVE TO WRITE TESTS.

I am more than happy to implement it if there are no objections.

**Comment by bendichter** [comment]
This sounds like a very good idea to me. Can anyone think of a way that it might backfire?

**Comment by mgrauer** [comment]
One problem is that the thresholds can be hard to get right or be too sensitive. Say you remove lines of code and the associated tests, your overall coverage can go down even though you haven't introduced any uncovered lines.

There is the Con that @dorukozturk pointed out where you now cannot add new lines of code without also covering them, which can be an impediment to development speed. Generally that is a good thing, to slow us down, but if you add boilerplate lines of code that don't need to be covered they can still trip the thresholds.

We could spend some time to tune the thresholds, but when someone is pushing hard for a deadline these can failing tests could be annoying.

Generally I think this is a good thing because it is a guard rail to encourage us to do the right thing. It can be overridden by admin authority (i.e. a failing test that can be forced to be merged), but at least it adds visibility.

**Comment by bendichter** [comment]
Yeah removing code+tests and adding boilerplate code do sound like possible failure modes, but I agree the pros seem to outweigh the cons and we can override if we need to.
