### ISSUE TITLE
ophys.ImagingPlane.imaging_rate should be float for consistency

### ISSUE THREAD

**Issue by elyall** [NeurodataWithoutBorders/pynwb#494]
Sampling frequencies are recorded in multiple locations. As far as I'm aware, in all but 1 of these locations it is referred to as "rate" and is specified as a float. 

In [ophys.ImagingPlane](http://pynwb.readthedocs.io/en/latest/pynwb.ophys.html?highlight=opticalchannel#pynwb.ophys.ImagingPlane) the sampling frequency is specified under "imaging_rate" as a string. 

I'd recommend changing the parameter name ("imaging_rate" -> "rate") and datatype (str -> float) for consistency.

**Comment by bendichter** [comment]
Great suggestion, @elyall. We are trying to separate development of the underlying schema from development of pynwb tools. Since this is a change to the schema, it would fit better in https://github.com/NeurodataWithoutBorders/nwb-schema. We have an open issue related to this at https://github.com/NeurodataWithoutBorders/nwb-schema/issues/136 but it does not mention the name change, which I think is important for consistency. Would you mind adding this to that issue?

**Comment by elyall** [comment]
Ah yes, should've realized that. I'll add my suggestion over there and close this issue.
