### ISSUE TITLE
Adding sweep based information

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#499]
# Current design

https://github.com/t-b/ipfx/blob/feature/sweep_table/sweeptables.md

# Old design

This is a POC design we've come up during the hackathon at the allen institute.

# Problem

In Icephys it is common to have sweeps (a group of PatchClampSeries belonging
together, were up to two TimeSeries are from one electrode, including
other TimeSeries not related to an electrode (aka TTL channels)).

Currently the concept of sweeps is not present in NWB so linking different
TimeSeries together is not possible.

# Goals

Allow to find the TimeSeries which are from one sweep without having to iterate over all present TimeSeries.

# Solution

Add some more tables

## Sweep Table (DynamicTable)

|Sweep number  | Vector of indizes into the acquisition table (vector column data) |
|------- | ----------------------------------------------- |
|        |                                                 |

## Acquisition Table (DynamicTable)

| Index | Sweep number | Soft link to electrode| Soft link to device | Stimulus (Soft link to TimeSeries) | neurodata_type of Stimulus TimeSeries | Acquisition (Soft link to TimeSeries) | neurodata_type of Acquisition TimeSeries |
 |---|--------|--------|---------------------|------------------------------------|------------------------------------|------------------------------------|------------------------------------|
 |        |        |                     |      |     |                                    |                                    |                                    |                                    |                                    |
 
The columns in the acquisition table could be reduced to the bare minimum: `Index, Stimulus (Soft link to TimeSeries), Acquisition (Soft link to TimeSeries)`.

Both tables live in `/general/intracellular_ephys`.
In the acquisition table entries which don't make sense are empty (e.g. no link to an electrode for TTL data).
The first column for both tables is an unique index.

**Comment by t-b** [comment]
Well be working on this feature starting now.

**Comment by oruebel** [comment]
@t-b you should consider using DynamicTable instead of compound type (at least if you want to enable users to dynamically add columns to the tables without having to create new extensions). DynamicTable did not exist yet when this issue was created but @ajtritt has been working on replacing most compound types with DynamicTable.

**Comment by t-b** [comment]
@oruebel Thanks for the hint. Yes we want to use the DynamicTable instead of compounds. I've adapted the issue text already.

**Comment by bendichter** [comment]
@t-b We're hoping to lock the core schema for 2.0 in pretty soon. Were you thinking this would be part of the core or would it be an extension?

**Comment by t-b** [comment]
@bendichter I hope to have that in core. When is soon?

**Comment by bendichter** [comment]
@t-b our goal is SfN, but we can be much more flexible if you can make this a non-breaking change i.e. if previously written files pass the validator after the change. If you are only adding classes and not changing existing classes, this should be the case.

**Comment by t-b** [comment]
@bendichter Thx. Originally the plan was to break existing files. But given the timeline I've reworked the design so that old files without these tables are still considered valid.

**Comment by bendichter** [comment]
@t-b Thanks! We are trying to accommodate users who need new features as well as users who need a stable schema.  I appreciate your flexibility on this, and I'm glad you are able to find a working solution! If in the end it isn't possible to do what you need without breaking changes, you always have the option of making this an extension instead of a change to the core.

**Comment by ajtritt** [comment]
@t-b you might consider making Sweep Table a DynamicTableRegion if it is just storing indices into the Acquisition table. If you want the flexibility of adding other information to the Sweep Table, you can leave it as a DynamicTable and make ***Sweep number*** a DynamicTableRegion

**Comment by t-b** [comment]
@ajtritt Thanks for the hints. I've cut down the original approach into https://github.com/t-b/ipfx/blob/feature/sweep_table/sweeptables.md. But I think you suggestions regarding DynamicTableRegion apply as well.

**Comment by ajtritt** [comment]
@t-b Sounds good. I just have one comment...

>  The PatchClampSeries groups `/root/acquisition/XXX` and `/root/stimulus/XXX` will gain a group attribute named sweep_number as 64-bit signed integer.

If you're just going to add an attribute to PatchClampSeries, you can make it optional, and it will still be backwards compatible. Although, I support the table approach over this, since it makes it easier for users to add additional data, and makes querying a file for datasets much more efficient.

**Comment by t-b** [comment]
@ajtritt My idea from the file was to combine both changes, I just splitted them up into the non-breaking changes and the breaking changes.

But maybe my idea of breaking vs non-breaking is wrong.

**Comment by ajtritt** [comment]
@t-b Ah, my bad, I see that now. I still think you could do this without that component being a breaking change. You have specified that, if nothing is passed for *sweep_number*, it defaults to -1, suggesting to me that it's not necessarily required. If that is in fact the case, making it completely optional (i.e. instead of defaulting to -1, default to not even setting the attribute) would allow you to add this later on without it breaking anything or necessitating an extension.

**Comment by t-b** [comment]
@ajtritt Okay, yeah I can make that an optional attribute. Thanks for the feedback.
