### ISSUE TITLE
adding a new dependency breaks tests

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#537]
## Bug

I added a new dependency to requirements.txt, and it causes the CircleCI tests to break. The test suite runs fine, but the wheel test break. 
See #536

**Comment by dorukozturk** [comment]
@ajtritt Adding pandas to [here](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/setup.py#L27-L34) should do it. This is happening because during wheel installation we are not installing dependencies but we are just relying on dependencies declared in setup.py. (See [here](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/tox.ini#L70))

**Comment by ajtritt** [comment]
Is there a solution that doesn't involve maintaining two lists of dependencies?

**Comment by dorukozturk** [comment]
Some people parse requirements.txt from their setup.py but I think adding too much logic to the setup.py is not a good thing. Actually those 2 lists serve different purposes. [Here](https://caremad.io/posts/2013/07/setup-vs-requirement/) is a great article which talks about the differences and best practices.

**Comment by oruebel** [comment]
@dorukozturk @ajtritt  can this issue be closed?

**Comment by dorukozturk** [comment]
The solution to this problem is trivial but it is kind of against python's packaging/requirement listing style. I lean more towards leaving it the way it is and closing this issue.
