### ISSUE TITLE
Have starting_time be 0.0 by default

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#542]
In my experience, the starting time of a `TimeSeries` is almost always `0.0`. Of course we should keep the flexibility to make it some other time if needed, but I think it's safe to assume if a user supplies a `rate` and no `timestamps` or `starting_time` that they mean `starting_time=0.0`. I propose that this be a default value for `TimeSeries` objects and all objects that inherit from `TimeSeries`.

**Comment by oruebel** [comment]
I think this is something for the API side. The problem is that it is a conditional default, i.e, if you use rate instead of timestamps than the default for starting_time would be 0 otherwise it would be None. You could implement this logic in the __inti__ function of TimeSeries. I don't think we need to change the schema for this.
