### ISSUE TITLE
python2 and python3 cross-compatibility

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#59]
I have been working on using six to gain cross-compatibility.  New dependencies include:

requests (replaces urllib in setup.py; cross-compat is rough in this library)
six
unittest2 (a python2 backwards-compatible substitute for unittest)

I also added some docker files building under 2 and 3 (and a script that drives them), to verify that all tests are passing.  ill point my PR to this issue to simplify merging; might make sense to label this as feature.  Happy to iterate if anything looks amiss

**Comment by nicain** [comment]
Hello @ajtritt @oruebel @dyf @mgrauer; I have been working on sketching out what would be required to implement python2/python3 cross-compatible pynwb.  I have created PR https://github.com/NeurodataWithoutBorders/pynwb/pull/60 that passes all of the current unit tests in both python2 and python3, using six and unittest2.

Mostly this was smooth sailing, however on PR review Andrew pointed out in https://github.com/NeurodataWithoutBorders/pynwb/issues/65 that pynwb/src/form/build/map.py uses __prepare__ (https://www.python.org/dev/peps/pep-3115/), a class method which replaces the local namespace inside the class body so that the class initialization can benefit from decorators.  @ajtritt please correct me if I am wrong here.

There doesn’t seem to be a good way to make this type of functionality backward compatible to python2, and so PR https://github.com/NeurodataWithoutBorders/pynwb/pull/60 moves these decorators outside of the class and uses them directly on the classes and methods that need them.

Deciding to do this is a significant decision, because it would constrain the functionality and implementation going forward, but would allow compatibility with code bases that are still reliant on python2.  Additionally, there would be nontrivial developer time needed as new features are added, to maintain the compatibility and handle any bug reports stemming from weird issues that might be missed.

Please reply below with your thoughts regarding this feature.

**Comment by oruebel** [comment]
@nicain thanks for exploring this issue. I'll have a look at your branch. Currently my feeling is that a) having Python 2 support is a significant benefit but also b) maintaining Python 2 and 3 simultaneously requires significant effort. Essentially it seems that we have two main options:

1) Maintain Python 2/3 compliant codes
----------------------------------------
**+** No separate versions and Python 2/3 are always in sync
**-** Python 2 developers introducing errors for Python 3 and vice/versa
**-** All developers have to know and maintain Python 2/3 compliance 
**-** Python 2 is scheduled to die in 2020 
**-** There is still a lot to do until the SfN release and making this switch right now would likely slow development
**-** Python 3 features and functionality that have no equivalent in Python 2 cannot be used. For example, advanced features such as i.e. advances features, such as [coroutines](https://docs.python.org/3/library/asyncio-task.html) and [\_\_prepare\_\_](https://docs.python.org/3/reference/datamodel.html#preparing-the-class-namespace) cannot be be used in cross-compatible code

2) Have a separate fork for Python 2
-------------------------------------
**+** Most developers can work in Python 3 only
**+** Clean code base, i.e, clear separation of Python 2 and 3
**+** Allows us to do Python 2 only for main releases
**+/-** One developers has to deal with porting and maintaining Python 2 
**+/-** Tests for Python 2 done independent of tests for Python 3
**-** Python 2 and 3 repos can become out-of-sync
**+** Python 3 branch can progress with the development with Python 3.x 

I would suggest that we schedule a phone call at some point during the next weeks to discuss this issue to define how we want to deal with this issue. Right now my inclination is that at least until SfN we might want to do this via separate forks to reduce the risk of not being able to complete the features we want for the release. Once we have completed the release, at which point most major changes should hopefully be done, we can then review what we are doing for Python2/3 to decide how we want to move forward in the long run. 

These are just my current thoughts. I still need to review the Python 2 port. I am open for discussion, but I think it would be helpful to do this in person via videocon at some point.

**Comment by neuromusic** [comment]
Yes, Python 2 is scheduled to die in 2020, but if this project doesn't support Python 2, I fear it will die in 2017. For Python developers at large, 2.x is still dominant. 

https://www.jetbrains.com/pycharm/python-developers-survey-2016/

Among scientist-developers (our primary target users), who generally lag behind developers at large, it is probably far larger than 70%.  My biggest concern with this project is that all of your hard work will be wasted because the community doesn't pick it up. I fear that requiring Python 3 is a major barrier to entry.

As such, I think the most important thing for the SfN release is that the project can be installed and used, even if all of the features we want aren't there yet. As much as my team's needs have more to do with features that we've highlighted, I think Python 2 support is more important for creating a "minimum viable product" the community at large.

Note: there's also another option:

3. only support python 2

This has all of the project management benefits of Python 3 only.

**Comment by oruebel** [comment]
@neuromusic just to clarify, in my opinion this discussion is not about Python 3 vs. 2 but on how we can best support both. @nicain has done a really nice job in getting Python 2 support going, and the question to me is not if we should support Py2 but what is the best strategy for doing so. I'll setup a videocon on this topic to discuss options so that we can hopefully decide on a clean strategy going forward within the next few weeks.

**Comment by neuromusic** [comment]
Happy to be in a videocon.

"Right now my inclination is that at least until SfN we might want to do this via separate forks to reduce the risk of not being able to complete the features we want for the release."

I think this makes sense. I'm game for the easiest way to have Py2 support for the SfN release.

**Comment by arokem** [comment]
From the peanut gallery: I think that having Python 3 support is important, and from my own experience maintaining 2/3 compatibility is not terrible (although admittedly a bit harder if your focus is file IO...). 

I believe that maintaining two forks would make your life harder than supporting 2/3 in parallel (for example, how do you make sure that fixes on one fork make it into the other fork?). 

If you do plan to support 2/3 in parallel, I think that having continuous integration (e.g., through Travis) would help you a lot. At the very least, you will avoid this one: 

>  Python 2 developers introducing errors for Python 3 and vice/versa

because everything would get tested on the CI on both versions, before it's merged. If you want me to implement CI on Travis for this, I could give it a go on a PR. Just let me know.

**Comment by oruebel** [comment]
@arokem thanks for the feedback! These are good points, and we will certainly consider them in our discussions.  

I agree that testing and CI are very important. Before the recent move of repos to GitHub we used to have CI implemented via Bitbucket pipelines. Our friends from Kitware will be working on setting up CI (and other items related to testing) on the GitHub repos. If you would like to help out with the CI efforts, then just let me know so that I can introduce you the Kitware team so that you can coordinate with them on the best path to contribute to that effort.

**Comment by mgrauer** [comment]
/cc @jcfr @kotfic @danlamanna

@arokem We would welcome working with you on the python 2/3 CI.  Please contact me through @oruebel , or contact me in the NWB slack channel and we can coordinate.  

I wish there was a way to do a direct message in GitHub...

**Comment by nicain** [comment]
@arokem @mgrauer FYI the dev branch has a Dockerfile for testing, and the Makefile has a rule "test_docker"; the python2 branch https://github.com/NeurodataWithoutBorders/pynwb/pull/60 has a similar Dockerfile for running the same tests under python2

**Comment by nicain** [comment]
@oruebel RE: writing python2/3 compatible codes: I think having some concrete information about the current code base would help in the discussion about the parallel vs compliant codes decision.

I have found the following types of changes necessary in pynwb to gain python2 compatibility:
1) Using requests instead of urllib.request in setup.py
2) Using six.raise_from to overcome “raise Exception from e” syntax
3) Using six.with_metaclass to overcome “class Foo(object, metaclass=Bar)” syntax
4) Using explicit super(Foo, self) instead of super()
5) Using unittest2 instead of unittest to get subtest functionality
6) Working around __prepare__ usage in  class DecExtenderMeta

The only challenging bit here is (6), worked around in https://github.com/NeurodataWithoutBorders/pynwb/pull/60/commits/849b0c1f32e208de6cc9830259b82e49f09f2739 

Are there other parts of the codebase that either you or @ajtritt are aware of that you think might pose a significant challenge to maintaining compatibility?

**Comment by oruebel** [comment]
@nicain thanks for this helpful summary.

**Comment by neuromusic** [comment]
to be clear, I also think that python 3 support is important

**Comment by neuromusic** [comment]
thanks to @arokem's input & @nicain's outline of necessary steps to move forward on @oruebel's proposed strategy 1: "Maintain Python 2/3 compliant codes", this sounds like the right approach to me.

I'm not sure that a videocon is necessary. This forum should be sufficient to consider the merits of different approaches & establishes a good precedent for open development of this community project.

Returning to @oruebel's pro/con list
- Python 2 developers introducing errors for Python 3 and vice/versa <- as @arokem noted, this can be addressed with CI
- All developers have to know and maintain Python 2/3 compliance <- yup, but @nicain has highlighted the key areas of concern
- Python 2 is scheduled to die in 2020 <- which means that we need to support Python 2 for 2.5 more years
- There is still a lot to do until the SfN release and making this switch right now would likely slow development <- perhaps, but better a Python2 compatible package by SfN than kicking the can down the road

I'd like to cast a vote that we move forward on maintaining a single Python2/3 compatible codebase. 

Let's get Travis CI setup ASAP so we can get #60 reviewed & merged.

**Comment by arokem** [comment]
I've added a very simple Travis configuration file on #84. 

For a sense of what that would look like (once you flip Travis on), check out this PR against my fork: 

https://github.com/arokem/pynwb/pull/1

It's passing on Python 3:

https://travis-ci.org/arokem/pynwb/jobs/265004881

but failing on Python2: 

https://travis-ci.org/arokem/pynwb/jobs/265004880

because of urllib.requests (mentioned above).

**Comment by arokem** [comment]
And here is my branch with the Travis configuration with all the changes implemented in #60: 

https://github.com/arokem/pynwb/pull/2

**Comment by arokem** [comment]
FWIW, looks like if you merge #84, and then rebase #60 on top of `dev`, the tests should all pass.

**Comment by nicain** [comment]
> I'm not sure that a videocon is necessary. This forum should be sufficient to consider the merits of different approaches & establishes a good precedent for open development of this community project.

I agree with @neuromusic, we don't need a videocon to make a decision here.  To that end:

> Are there other parts of the codebase that either you or @ajtritt are aware of that you think might pose a significant challenge to maintaining compatibility?

@oruebel @ajtritt Having developed almost all of the code here, your perspective is critical here.  Are there any design considerations (besides the use of __prepare__ in DecExtenderMeta) that are both 1) not python2 backwards compatible, and 2) are not easily fixable by six, unittest2, etc?  Having a list of these problem spots is key (I hope there are none, given our ~90% test coverage); if there is really no serious incompatibilities, I vote we go ahead with maintaining Python 2/3 compliant codes.  If there is an as-yet unappreciated underlying design consideration that makes this too painful, lets look at it together.

As a side note, http://python3porting.com/strategies.html is pretty useful here.  http://python3porting.com/strategies.html#python-modules-and-packages suggests the compliant code model for this type of project.  Compare this against http://python3porting.com/strategies.html#separate-branches-for-python-2-and-python-3, in light of the rapidly changing code base (daily, sometimes hourly) and dealing with package distribution complexity.

**Comment by oruebel** [comment]
@nicain @neuromusic this is a major decision that has broad implications, that is why I think having a videocon on this will be useful and much more efficient in terms of time. I'll send out an invite soon. 

Given the amount of work left before the release, my preference right now is to at least until the SfN release to maintain Python 2 in a separate fork.

**Comment by ajtritt** [comment]
I agree with @oruebel on this issue... I appreciate the enthusiasm to charge ahead, but this decision has major implications for development, so we really need to take the time to flush out the options.

Here are my thoughts on the issues that have been raised thus far:

1. As simple as writing 2/3 compatible code might seem, the minimal up-front costs comes with a significant trade-off. Writing cross-compatible code limits us to only features of Python 3 that have an equivalent in Python 2. Given that Python 3.x is the future, we need to make writing a codebase that can evolve with the progression of 3.x a priority. To be more specific, there are many features of 3.x that could be useful, but we are not able to use because they have no equivalent in Python 2. The PyNWB codebase already uses one of these i.e. \_\_prepare\_\_. By keeping a separate Python 2 fork for releases, we can actively develop in Python 3.x and deal with 2 vs. 3 differences at release time. 

2. Writing cross-compatible code has one more subtle, yet significant implication. Strings are unicode in Python 3, and ASCII in Python 2. This means that the 2/3 compatible code needs ASCII when run in Python 2, but can use unicode when run in Python 3. So, our codebase would behave drastically different when run in different version of Python. An example of this is when h5py writes strings--the same line of code (`h5py.special_dtype(vlen=str)`), writes UTF-8 in Python 3, but writes ASCII in Python 2.  

3. The issue of a rapidly changing code base is really the result of early development. There has yet to be a stable release--we are really still in alpha. Upon reaching a stable release, I do not see PyNWB being a rapidly changing the code base in the long-term.

**Comment by nicain** [comment]
I see a middle path forward.  Given the following constraints:

1) The core developers prefer to develop in python3, because they have the vision for the long-term stability, maintenance, and adoption of the code.
2) The strong majority of the end-users will require fully featured support for python2 in the short term.  The Allen Institute requires this support as soon as possible, and cannot use this software in production without this support (@dyf correct me if I am wrong here).
3) We need to assist the community’s transition to python3, for longevity.

To satisfy all of these I propose:

1) The core code (dev branch, and all PR’s to it) be developed in python3, but not including any features that are not somehow back-portable to python2. CI will run for dev in python3 only, however all features must have a back-ported python2 implementation that still pass tests (even if the backport gets kinda messy, like in https://github.com/NeurodataWithoutBorders/pynwb/pull/60 src/form/build/map.py).  
2) We maintain a second dev branch (I vote to call it dev6) that supports python2.7 and python3 under CI (but not earlier 2.x). This branch is downstream of dev and also supported by the core dev team.  After alpha ends in November, dev6 is the basis of master, because many end-users in the short term will need this functionality (Constraint 2 above), however it should also support python3 so that we can facilitate community transition to python3 (Constraint 3 above), while still being fully featured.  

This addresses the two main issues of maintaining two separate forks: guaranteeing equivalent functionality (for this to work, dev must maintain high test coverage, maybe >90% seems right to me; @ajtritt and @oruebel have established a great precedent for this already), and the distribution difficulties associated with having python2 users aimed at one branch and python3 users aimed at another (both are aimed at a python2/3 master).  This will cost us the ability to implement any features in the short run that cannot be back-ported, but these would cost us our (mostly python2) user-base anyways.

At a pre-defined later date (I propose some time in 2020, when python2 is officially phased out), we drop the guarantee of full-featured python2 support.  We make a major revision number increment, master becomes downstream of dev, and we get back a nice and neat python3 codebase to support long-term development (again, Constraint 1 above), without sacrificing any functionality.  dev6 gets renamed to legacy, and is maintained ad-hoc with a warning that it is not guaranteed to be fully featured (although at the time of transition, it will be, by definition).  Also this point, obviously, the backwards-compatible feature restriction is removed on code PR’ed to dev.  If we all agree to this, we should additionally make this decision prominent on a milestone page on the repo, along with the rationale behind it as early as possible (and definitely before November).

Then we make a plan to deal with python4 :)

**Comment by mgrauer** [comment]
It sounds like there is already a calendar related to release that I'm unaware of.  Can someone point me to that or can we discuss it on the video call?  What I'm interested in is whatever promises or expectations have been set for any releases, along with release versions, as well as adherence to semantic versioning or other means of providing contracts around the API surface and backwards compatibility.

**Comment by nicain** [comment]
Thanks all for the great videocon today.  FWIW, I just updated the branch for PR https://github.com/NeurodataWithoutBorders/pynwb/pull/60 to be downstream of the current neurodatawithoutborders/dev, and it was very easy (took 1 minute).  THe only human change was a super() to super(BaseStorageSpec, self).

**Comment by oruebel** [comment]
Thanks @nicain. I'll post the summary of our discussion here once we have finalized the google doc.

**Comment by ajtritt** [comment]
resolved by PR #98
