### ISSUE TITLE
Add support for dtype: bool to specification language

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#658]
## 2) Feature Request
Add the ability to specify dtype as a `bool` to the specification language.

See [here](https://schema-language.readthedocs.io/en/latest/specification_language_description.html#dtype) for available dtypes

Here are the following sections that need attention:
- [ ] [form.spec](https://github.com/NeurodataWithoutBorders/pynwb/blob/f671b8d7c8692e48fadd3e6314856ff3bd642421/src/pynwb/form/spec/spec.py#L25)
- [ ] [h5tools](https://github.com/NeurodataWithoutBorders/pynwb/blob/f671b8d7c8692e48fadd3e6314856ff3bd642421/src/pynwb/form/backends/hdf5/h5tools.py#L432)

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by t-b** [comment]
h5py maps numpy's bool to HDF5 enums, see http://docs.h5py.org/en/stable/faq.html#what-datatypes-are-supported.

I've looked into Igor Pro and Matlab, both support reading and writing enums!

**Comment by bendichter** [comment]
https://github.com/NeurodataWithoutBorders/nwb-schema/issues/175

**Comment by bendichter** [comment]
> h5py maps numpy's bool to HDF5 enums

Does anyone else find this strange? Doesn't HDF5 natively support boolean values? What could be the reason for not using them?

**Comment by oruebel** [comment]
> Does anyone else find this strange?

At least in older versions of HDF5 this is because the C programing language does not have a boolean data type. See https://support.hdfgroup.org/HDF5/hdf5-quest.html#bool

On a separate note, since there seems to have been some confusion in the other threads. A Boolean is usually 8bit long (not 1 bit)(otherwise it would not be addressable). Storing a bool and an 8bit int is from a storage/memory perspective, hence, the same, the only difference is that bool only allows ``00000001`` and ``00000000`` as values.

**Comment by t-b** [comment]
And the reason to use a bool array instead of 8bit integer array is speed. The single bits might not be adressable, but having a bunch of them in a vector makes for a very compact and fast datastructure. See [here](https://isocpp.org/blog/2012/11/on-vectorbool) for some thoughts on that (requiring C++ though).

Unfortunately not everyone is using optimized algorithms for bools.

```python
import numpy as np

x = np.ones(16, dtype=np.bool_)
np.save("ones", x)

x = np.zeros(16, dtype=np.bool_)
np.save("zeros", x)
```
```bash
$ python test.py

$ od -x ones.npy
0000000 4e93 4d55 5950 0001 0046 277b 6564 6373
0000020 2772 203a 7c27 3162 2c27 2720 6f66 7472
0000040 6172 5f6e 726f 6564 2772 203a 6146 736c
0000060 2c65 2720 6873 7061 2765 203a 3128 4c36
0000100 292c 202c 207d 2020 2020 2020 2020 0a20
0000120 0101 0101 0101 0101 0101 0101 0101 0101
0000140

$ od -x zeros.npy
0000000 4e93 4d55 5950 0001 0046 277b 6564 6373
0000020 2772 203a 7c27 3162 2c27 2720 6f66 7472
0000040 6172 5f6e 726f 6564 2772 203a 6146 736c
0000060 2c65 2720 6873 7061 2765 203a 3128 4c36
0000100 292c 202c 207d 2020 2020 2020 2020 0a20
0000120 0000 0000 0000 0000 0000 0000 0000 0000
0000140
```

Here the 16 bools take 32 bytes whereas you could have packed them in 2.

**Comment by oruebel** [comment]
@t-b just to avoid confusion in terms of terminology, when using single bits these are usually referred to as bitarrays (since bool  array usually refers to an array of bytes). While bitarrays are more compact, they require special data structures to deal with issues, e.g.: i) the need for padding if your array length is not divisible by 8, ii) require custom access and operator APIs etc.. Unfortunately many common programming languages (Matlab, Python, C/C++ etc.) do not have native support for bitarrays, making them problematic from a usability perspective. Bitarrays have there applications and are clearly useful, but from a the perspective of exchanging data I think they are really mainly useful if the arrays are very large (many GB) where performance issues become more critical. 

However, I think we should create a separate issue for this discussion. This issue ticket is for adding a standard bool (1byte) as a dtype. The discussion regarding bitarray should be moved to a separate issue on bitarray. Also, note that bitarrays are not as simple as defining ``dtype=bit`` as we also need additional information alongside the array, e.g., the number of valid bits (since storage is always in byte increments). As such bitarrays would likely require a separate neurodata_type rather than just a dtype.
