### ISSUE TITLE
Data and arguments evaluated lazily

### ISSUE THREAD

**Issue by ageorgou** [NeurodataWithoutBorders/pynwb#666]
I came across something that (to me) seems unintuitive, and that I am not sure is intended behaviour. I'll start with a minimal example and then explain the real use case.

If I run the following code:
```python
from datetime import datetime

import numpy as np
from pynwb import NWBFile, NWBHDF5IO, TimeSeries

nwbfile = NWBFile('PyNWB tutorial', 'demonstrate NWBFile basics', 'NWB123', datetime.now())

# Add a timeseries
# data = list(range(0, 100, 10))
data = np.arange(0, 100, 10)
timestamps = list(range(10))
test_ts = TimeSeries('test_timeseries', 'PyNWB tutorial', data, 'SIunit', timestamps=timestamps)
nwbfile.add_acquisition(test_ts)

# data[:] = [2*x for x in data]
data[:] = 2 * data
new_ts = TimeSeries('new_timeseries', 'PyNWB tutorial', data, 'SIunit', timestamps=timestamps)
nwbfile.add_acquisition(new_ts)
with NWBHDF5IO('basic_example.nwb', 'w') as io:
    io.write(nwbfile)
```
and then view the file, both timeseries have the same data. It appears that the timeseries are not created with the contents of their arguments, only a reference, and then the data is only checked on writing. This seems counterintuitive to me, so I thought I would check that it is intentional. This happens whether I use plain lists or NumPy arrays.

In reality, the problem emerged when I was adding mulitple planes with similar manifolds. I was using a single NumPy array, modifying the elements which changed between each plane, and then passing that to `create_imaging_plane`:
```python
manifold = ... # initial template
for i in range(N):
    manifold[:, :, 2] = changing_value(i)
    self.nwb_file.create_imaging_plane(
                name=name, source="source",
                [...]
                manifold=manifold
    )
```

I can work around this by creating a new array for the manifold each time, but I'm worried about the memory usage. I could also write the file after creating each plane, but I'd like to avoid repeated writes (because of the time it takes). I haven't tried keeping the file open in append mode as I was having problems with using that, but I suppose that might speed up the successive writes if I can get it working?

This is with PyNWB version 0.5.1.

Any help or advice is appreciated!

**Comment by ajtritt** [comment]
@ageorgou If I understand you correctly, this is intentional, and not a PyNWB-specific issue. This is just the behavior of passing by reference. From what you are saying, it sounds like you're expecting PyNWB to behave as if passing by value, which, for the purposes of this discussion, we can say Python does not do. (This is issue is more nuanced than I am making it sound, so I suggest you look this up on your own for a more thorough explanation) 

To get the pass-by-value behavior you expect, we would have to make copies of all the values passed in, which we do not and have no intention of ever doing. We do not make copies of passed values under the hood, for obvious reasons. Copying the data you pass in would be the only way to ensure that the state of the variable you passed in is held onto in the created container and subsequently written to disk. Copying the data of course, would create the memory usage problems you are trying to avoid. Unfortunately, there's no way around this for you.

**Comment by ageorgou** [comment]
Thanks for the clarification @ajtritt. I was indeed expecting PyNWB to copy the values or at least consume them directly (for example, creating an array if a list is passed). I will adjust accordingly.

**Comment by oruebel** [comment]
If memory is an issue for you could potentially look at ``H5DataIO`` and /or``DataChunkIterator`` to create your manifold array on the fly when it is being written.

**Comment by ageorgou** [comment]
@oruebel Thanks, I've looked into the iterative writing before. I'll keep that in mind when checking with the full datasets.
