### ISSUE TITLE
Type promotion logic does not take into account the signedness for integer types

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#698]
Build the `icephys.py` example in docs/gallery/domain.

Look into the nwb file with `h5dump icephys_example.nwb  | grep -C 10 conversion`:

```
          ATTRIBUTE "conversion" {
             DATATYPE  H5T_IEEE_F64LE
             DATASPACE  SCALAR
             DATA {
             (0): 1e-012
             }
          }
```

So the conversion attribute is stored as 64bit IEEE float little endian (aka double).
But the YAML file `nwb.base.yaml` says

```
    - name: conversion
      dtype: float32
      doc: Scalar to multiply each element in data to convert it to the specified
        unit
      default_value: 1.0
      required: false
```

So they both don't agree.

Where are the types in HDF5 decided? And from what data?

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Python
- **Python Version:** Python 3.6
- **Operating System:** Windows
- **Pynwb Version:** dev branch form today

**Comment by t-b** [comment]
This case seems a bit academic but in my current case a 32bit signed integer is created where I specified a 64bit unsigned integer in the YAML file.

**Comment by oruebel** [comment]
Currently the number of bits in the specification language defines a minimum number of bits,rather than the absolute. See the note box in this section https://schema-language.readthedocs.io/en/latest/specification_language_description.html#dtype . That being said, I'm not sure right now where this is being enforced in PyNWB. To force 32bit float my guess is that you would probably have to explicitly use a numpy 32bit scalar right now. I'd have to look through the code to give you a more precise answer but maybe @ajtritt knows the off the top of his hat what the right answer is.

**Comment by t-b** [comment]
@oruebel Thanks for the reply. The float was just for illustration. My real issue is for integers that the signedness is not respected.

Example:
- Repo: https://github.com/t-b/pynwb/tree/uint-yaml-issue-698
- Build `python docs/gallery/domain/icephys.py`
- Look into it with `h5dump icephys_example.nwb  | grep -A 5 sweep`

```
            ATTRIBUTE "sweep_number" {
               DATATYPE  H5T_STD_I32LE
               DATASPACE  SCALAR
               DATA {
               (0): -1
               }
```

Sweep number is defined as

```
  - name: sweep_number
    dtype: uint64
    doc: 'Sweep number, allows to group different PatchClampSeries together.'
    required: false
```

But a signed integer is written into the HDF5 file. So the promotion logic failed here.

**Comment by oruebel** [comment]
It looks like uint64 is missing in the list of dtypes in h5tools https://github.com/NeurodataWithoutBorders/pynwb/blob/56c0ddabcfc1d0f10d2f0ee102d94abce76653ed/src/pynwb/form/backends/hdf5/h5tools.py#L446-L473 I'm not sure if that's the root of the issue but it may be since you are using uint64 in the schema.
