### ISSUE TITLE
Shape of TwoPhotonSeries data

### ISSUE THREAD

**Issue by ageorgou** [NeurodataWithoutBorders/pynwb#722]
With the latest `dev` version (dea0722), attepting to create a `TwoPhotonSeries` with 2d data (512 x 512) gives an error:

```python
ValueError: incorrect shape for 'data' (got '(512, 512), expected '([None, None, None], [None, None, None, None])')
```

According to #706 and the error, the shape should be either 3d or 4d, which seems surprising. I also see that #706 [changed the data used in a relevant test]( tests/integration/ui_write/test_ophys.py) from 2d to 4d, but I don't know whether this means that the previous usage was incorrect.

Should it be possible to create a `TwoPhotonSeries` with 2d data?

**Comment by oruebel** [comment]
TwoPhotonSeries is a TimeSeries, i.e., the first dimension for should (if only for consistency) always be time. I.e., in your case of a single 2D image I think it should be (1 x 512 x 512).

**Comment by bendichter** [comment]
@ageorgou thanks for the error report. I just pushed a pretty big change to pynwb. The schema has always specified shapes for dataset, and we just started enforcing these shapes in pynwb. Although I was careful to match the schema, it is possible that I have made mistakes. There might also be cases where the schema shape does not work for some users- which we can now identify. Please continue to bring these shape issues up as they arise. It's crucial that the size constraints match the needs of the community.

In this case I agree with Oliver that, since `TwoPhotonSeres` extends from `TimeSeries`,  the first dim should always be time (or in this case frame). This constraint is specified explicitly in `TwoPhotonSeries`'s parent, `ImageSeries`:

https://github.com/NeurodataWithoutBorders/pynwb/blob/dea07228b48bde3441338f7b1e0a4b2021df96fe/src/pynwb/data/nwb.image.yaml#L34-L70

If you want to store a static image, you can use this structure with a single frame, or you should use the new neurodata_type, `GrayscaleImage`

**Comment by ageorgou** [comment]
Thanks @bendichter, @oruebel. I see why I thought there was a mismatch now, since we only had a single frame.

@bendichter The shape checking is already helping catch errors in usage, so thanks! The only thing I noticed in addition to this is that the `timestamps` for `ImageSeries` and `TwoPhotonSeries` don't have a shape specified - in contrast to, say, `SpatialSeries`. Again, though, not sure if this was intentional or not.

**Comment by bendichter** [comment]
@ageorgou good catch :-)
