### ISSUE TITLE
vectorindex has redundant methods

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#724]
[see here](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/core.py#L350)
```
    def add_vector(self, arg):
        self.target.extend(arg)
        self.data.append(len(self.target))

    def add_row(self, arg):
        self.target.extend(arg)
        self.data.append(len(self.target))
```
Maybe these are for compatibility, and/or one ought to be deprecated?

**Comment by bendichter** [comment]
@NileGraddis thanks for pointing this out. The reason for this is that we previously had two types: `VectorData` and `TableColumn` which were essentially the same so we decided to combine them. Since the structure can be used outside of tables, we decided to keep `VectorData` and remove `TableColumn` altogether. This looks like a piece that is leftover from that. When `VectorData` is used as a column of a dynamic table, it is more intuitive for this method to be called "`add_row`", so your guess about it being for compatibility was right. @ajtritt knows the details better than me.

I agree that it's not ideal to have the exact same code in two different methods. How would the team feel about just having `add_row` call `add_vector`? This shouldn't cause any user-side changes to the API.

**Comment by bendichter** [comment]
@NileGraddis in case you didn't know, github has a nifty trick for linking to code. When you select the code you can use [shift] to select multiple lines, then you can select Permalink from the [...] menu. If you post that link bare to the thread, it shows the code and give you a link, like so:

https://github.com/NeurodataWithoutBorders/pynwb/blob/dea07228b48bde3441338f7b1e0a4b2021df96fe/src/pynwb/core.py#L350-L356
