### ISSUE TITLE
adding units with spike times is slow

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#728]
I ran into some performance issues while attempting to write spike times for some of our extracellular ephys units. This manifested as a long runtime as well as high memory consumption.

In order to investigate further, I wrote [a script](https://gist.github.com/NileGraddis/96c70d1827c9b37333dafdcb2835703c) which generates and writes equivalent data using numpy and h5py.

Here are the results of cProfiling these functions (first and last lines) on my laptop with 100000 max times per unit:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.005    0.005   24.037   24.037 slow_unit_spike_times.py:34(with_nwb)
4468/1132    0.017    0.000   23.581    0.021 utils.py:358(func_call)
1150/1133    0.002    0.000   23.402    0.021 utils.py:266(call_docval_func)
        1    0.000    0.000   21.506   21.506 h5tools.py:189(write)
        1    0.000    0.000   21.506   21.506 io.py:36(write)
      9/1    0.000    0.000   18.470   18.470 map.py:139(build)
      5/1    0.000    0.000   18.470   18.470 map.py:1367(build)
      5/1    0.000    0.000   18.453   18.453 map.py:608(build)
     16/1    0.000    0.000   18.449   18.449 map.py:773(__add_groups)
     17/9    0.000    0.000   18.441    2.049 map.py:814(__add_containers)
       16    0.000    0.000   18.106    1.132 map.py:754(__add_datasets)
        3    4.334    1.445   18.093    6.031 map.py:659(__is_reftype)
 56318325   13.757    0.000   13.757    0.000 {built-in method builtins.hasattr}
        1    0.000    0.000    3.036    3.036 h5tools.py:401(write_builder)
      8/6    0.000    0.000    3.031    0.505 h5tools.py:535(write_group)
        8    0.000    0.000    3.031    0.379 h5tools.py:598(write_dataset)
        4    0.015    0.004    3.025    0.756 h5tools.py:840(__list_fill__)
        4    0.265    0.066    3.009    0.752 dataset.py:508(__setitem__)
       53    2.744    0.052    2.744    0.052 {built-in method numpy.core.multiarray.array}
       51    0.000    0.000    2.744    0.054 numeric.py:433(asarray)
     1129    0.002    0.000    1.889    0.002 file.py:475(add_unit)
     1129    0.003    0.000    1.712    0.002 misc.py:202(add_unit)
     1129    0.011    0.000    1.662    0.001 core.py:1032(add_row)
     1129    0.003    0.000    1.643    0.001 core.py:354(add_vector)
     1129    0.002    0.000    1.637    0.001 core.py:287(extend)
     1134    1.635    0.001    1.635    0.001 {method 'extend' of 'list' objects}
        1    0.009    0.009    0.995    0.995 slow_unit_spike_times.py:11(with_h5)
```
I additionally notice much more memory consumption when the pynwb version is running, but haven't explicitly profiled it. 

One possibility is that pynwb is writing some data that I'm not, which would account for the extra time and space. However, running `du` shows that the files are the same size:
```
430M	./slow_unit_spike_times.nwb
430M	./slow_unit_spike_times.h5
```
This also suggests that pynwb is not doing extra compression - another thing that could account for the additional work. I followed up by verifying that [this block](https://github.com/NeurodataWithoutBorders/pynwb/blob/4f3d3c6697c4e0af0d5d7a31dbcc46c94a4f90db/src/pynwb/form/backends/hdf5/h5tools.py#L615) was never entered. 

Maybe I'm approaching this wrong? Is there a more performant way to write these data?

**Comment by oruebel** [comment]
I think it would be useful to nail down a bit more which specific part of the process is slow. Also, as far as I can tell in the profiling data the results from the two calls (with base h5py and NWB) are intermixed in the statistics, i.e., it would be useful to run these separately to get independent profiles.

If you do ls, I think you will also see that the files are most likely not exactly the same size, because the nwb file should contain a number of additional groups and datasets. The difference is probably just few kb (which is why du shows the size in MB), but they should not be identical. I don't think this should matter with regard to performance, though.

Generally speaking, a certain slow-down is expected since PyNWB has to first map all the frontened containers to builders for write. However, I would not expect that the difference should be 24x. From the profile, I can't really tell right now which step is slow, i.e.: the 1) creation of the data in memory, 2) creation of the writer, 3) mapping and construction of the builders, or  4) the actual write. 
My guess is that the slow-down is probably somewhere in the mapping process but I can't tell without a deep dive. Unfortunately, I won't be able to do this myself this week, but if you can dive a bit deeper into PyNWB what part of the write is slow, that would be useful. Maybe @ajtritt has some ideas.

**Comment by nicain** [comment]
@ajtritt @oruebel Can we prioritize this issue?  We are currently blocked on generating our NWB files by this slow write-time.  Do you need more information from @NileGraddis or @nicain to help get started on this?

**Comment by oruebel** [comment]
I did some additional profiling based on the script that @NileGraddis provided and it looks like the culprit for the slow performance is``pynwb.form.build.map.ObjectMapper.__is_reftype``

https://github.com/NeurodataWithoutBorders/pynwb/blob/6683635cac7a0d4b6a08c97e6d485acebef194bd/src/pynwb/form/build/map.py#L659-L674

I basically ran Niles example as follows``with_nwb("temp2.nwb", 1129, 100000)`` (this gives me an ~437MB file). Constructing the data itself took ~3.6s and the write took ~23.8s and off that time, ~20s were spent in ``__is_reftype`` alone. Specifically, the issues seems to be when writing the container ``spike_times-(<class 'pynwb.core.VectorData'>)``.  The ``__is_reftype`` function is called from ``ObjectMapper.build`` here:

https://github.com/NeurodataWithoutBorders/pynwb/blob/6683635cac7a0d4b6a08c97e6d485acebef194bd/src/pynwb/form/build/map.py#L647

and then inside ``__is_reftype`` the function seems to iterate over each element of the ``spike_times`` array (which is a list of floats with the spike times) here:

https://github.com/NeurodataWithoutBorders/pynwb/blob/6683635cac7a0d4b6a08c97e6d485acebef194bd/src/pynwb/form/build/map.py#L663

For every element the function then checks the condition ``hasattr(t, '__len__') and ...``. Since the elements of the array are floats this evaluates to False every time so that the function ends up checking each element. This also explains the large number of calls to ``{built-in method builtins.hasattr}`` in the trace. 

It looks like if I just shortcut the loop when the first element is a float that the tests still pass and it cuts down the time for write to a much more reasonable 3.8s

```
            for t in tmp:
                if isinstance(t, float):
                    break
               if hasattr(t, '__len__') an....
```

However, I think that may not be actually the right fix, but rather a cheap hack ;-) I'm honestly not sure right now what the correct fix for this behavior is. @ajtritt can you have a quick look to see what the right fix should be.

**Additional comments**

Just to avoid confusion of what is actually being written. Nile's ``with_h5`` function writes:

![temp_h5](https://user-images.githubusercontent.com/10999845/48743757-55a4c780-ec19-11e8-840a-1a71300fb4f7.png)

And the full NWB file from ``with_nwb`` looks like this:

![temp_nwb](https://user-images.githubusercontent.com/10999845/48743759-59d0e500-ec19-11e8-8db4-2dcea3cdbacc.png)

On a separate note. While the time to construct the data is also longer, I think that is probably expected since ``DynamicTable.add_row`` (as a result of ``NWBFIle.add_unit`` is probably much more involved then a simple append (although I have not looked closer at this part).

**Comment by ajtritt** [comment]
@oruebel that seems like a reasonable fix for now. It might be worth adding a check for other types (i.e. int, bool, etc). 

In the long term, this function should not get called. the dtype for `spike_times` is specified, so that information should be able to be passed through. #633 will address this.

**Comment by oruebel** [comment]
Thanks @ajtritt for having a look at this. I just put in a corresponding PR.
